--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2026-03-30 14:18:35.189289)
-- B-ASIC version: 0.1.0.dev841+unknown.g4a216b396
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity memory24 is
    port (
        clk : in std_logic;
        en : in std_logic;
        schedule_cnt : in unsigned(8 downto 0);
        p_0_in : in std_logic_vector(31 downto 0);
        p_0_out : out std_logic_vector(31 downto 0)
    );
end entity memory24;

architecture rtl of memory24 is

    -- HDL memory description
    type mem_type is array(0 to 0) of std_logic_vector(31 downto 0);
    signal memory : mem_type;

    -- Memory address generation
    signal read_port_0 : std_logic_vector(31 downto 0);
    signal read_adr_0 : unsigned(0 downto 0);
    signal read_en_0 : std_logic;
    signal write_port_0 : std_logic_vector(31 downto 0);
    signal write_adr_0 : unsigned(0 downto 0);
    signal write_en_0 : std_logic;

    -- Address generation multiplexing signals
    signal write_adr_0_0_0 : unsigned(0 downto 0);
    signal write_en_0_0_0 : std_logic;
    signal read_adr_0_0_0 : unsigned(0 downto 0);
    signal read_en_0_0_0 : std_logic;

    -- Type conversion for interface
    signal p_0_in_internal : std_logic_vector(31 downto 0) := (others => '0');
    signal p_0_out_internal : std_logic_vector(31 downto 0) := (others => '0');
    signal forward_ctrl : std_logic;

begin


    -- Type conversions
    p_0_in_internal <= p_0_in;
    p_0_out <= p_0_out_internal;

    -- Control signal registers
    control_regs_proc: process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                read_adr_0 <= read_adr_0_0_0;
                read_en_0 <= read_en_0_0_0;
                write_adr_0 <= write_adr_0_0_0;
                write_en_0 <= write_en_0_0_0;
            end if;
        end if;
    end process control_regs_proc;

    -- Memory
    mem_0_proc: process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                if write_en_0 = '1' then
                    memory(to_integer(write_adr_0)) <= write_port_0;
                end if;
            end if;
        end if;
    end process mem_0_proc;
    read_port_0 <= memory(to_integer(read_adr_0));
    write_port_0 <= p_0_in_internal;

    -- Input and output assignments
    output_reg_proc: process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                case schedule_cnt is
                    when "101000011" => forward_ctrl <= '0';
                    when others => forward_ctrl <= '-';
                end case;
                if forward_ctrl = '1' then
                    p_0_out_internal <= p_0_in_internal;
                else
                    p_0_out_internal <= read_port_0;
                end if;
            end if;
        end if;
    end process output_reg_proc;

    --
    -- Memory write address generation
    --
    mem_write_address_proc: process(schedule_cnt)
    begin
            case schedule_cnt is
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101000011" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                when others =>
                    write_adr_0_0_0 <= (others => '-');
                    write_en_0_0_0 <= '0';
            end case;
    end process mem_write_address_proc;


    --
    -- Memory read address generation
    --
    mem_read_address_proc: process(schedule_cnt)
    begin
            case schedule_cnt is
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101001101" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101001111" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101011001" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101011010" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101100011" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101100101" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101110000" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(324, <b_asic.port.OutputPort object at 0x7fee269ffbb0>, {<b_asic.port.InputPort object at 0x7fee269ffa70>: 46, <b_asic.port.InputPort object at 0x7fee269ffe30>: 13, <b_asic.port.InputPort object at 0x7fee269fff20>: 24, <b_asic.port.InputPort object at 0x7fee26a18050>: 35, <b_asic.port.InputPort object at 0x7fee26a18140>: 46, <b_asic.port.InputPort object at 0x7fee26a18230>: 57, <b_asic.port.InputPort object at 0x7fee26a18320>: 11, <b_asic.port.InputPort object at 0x7fee26a18410>: 13, <b_asic.port.InputPort object at 0x7fee2697b840>: 23, <b_asic.port.InputPort object at 0x7fee269457c0>: 33, <b_asic.port.InputPort object at 0x7fee26a18500>: 57}, 'addsub322.0')
                when "101111011" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                when others =>
                    read_adr_0_0_0 <= (others => '-');
                    read_en_0_0_0 <= '0';
            end case;
    end process mem_read_address_proc;

end architecture rtl;

