--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2026-03-23 13:07:23.290141)
-- B-ASIC version: 0.1.0.dev896+unknown.gb95ecb04c
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity memory0 is
    port (
        clk : in std_logic;
        en : in std_logic;
        schedule_cnt : in unsigned(6 downto 0);
        p_0_in : in std_logic_vector(31 downto 0);
        p_0_out : out std_logic_vector(31 downto 0)
    );
end entity memory0;

architecture rtl of memory0 is

    -- HDL memory description
    type mem_type is array(0 to 6) of std_logic_vector(31 downto 0);
    signal memory : mem_type;

    -- Memory address generation
    signal read_port_0 : std_logic_vector(31 downto 0);
    signal read_adr_0 : unsigned(2 downto 0);
    signal read_en_0 : std_logic;
    signal write_port_0 : std_logic_vector(31 downto 0);
    signal write_adr_0 : unsigned(2 downto 0);
    signal write_en_0 : std_logic;

    -- Address generation multiplexing signals
    signal write_adr_0_0_0 : unsigned(2 downto 0);
    signal write_en_0_0_0 : std_logic;
    signal read_adr_0_0_0 : unsigned(2 downto 0);
    signal read_en_0_0_0 : std_logic;

    -- Type conversion for interface
    signal p_0_in_internal : std_logic_vector(31 downto 0) := (others => '0');
    signal p_0_out_internal : std_logic_vector(31 downto 0) := (others => '0');
    signal forward_ctrl : std_logic;

begin


    -- Type conversions
    p_0_in_internal <= p_0_in;
    p_0_out <= p_0_out_internal;

    -- Control signal registers
    control_regs_proc: process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                read_adr_0 <= read_adr_0_0_0;
                read_en_0 <= read_en_0_0_0;
                write_adr_0 <= write_adr_0_0_0;
                write_en_0 <= write_en_0_0_0;
            end if;
        end if;
    end process control_regs_proc;

    -- Memory
    mem_0_proc: process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                if write_en_0 = '1' then
                    memory(to_integer(write_adr_0)) <= write_port_0;
                end if;
            end if;
        end if;
    end process mem_0_proc;
    read_port_0 <= memory(to_integer(read_adr_0));
    write_port_0 <= p_0_in_internal;

    -- Input and output assignments
    output_reg_proc: process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                case schedule_cnt is
                    when "0010000" => forward_ctrl <= '1';
                    when "0010001" => forward_ctrl <= '1';
                    when "0010010" => forward_ctrl <= '0';
                    when "0011010" => forward_ctrl <= '0';
                    when "0011011" => forward_ctrl <= '0';
                    when "0011100" => forward_ctrl <= '0';
                    when "0011101" => forward_ctrl <= '0';
                    when "0011110" => forward_ctrl <= '0';
                    when "0101101" => forward_ctrl <= '0';
                    when "0110100" => forward_ctrl <= '0';
                    when "0110101" => forward_ctrl <= '0';
                    when "0110111" => forward_ctrl <= '0';
                    when "1000000" => forward_ctrl <= '1';
                    when "1000100" => forward_ctrl <= '1';
                    when "1000101" => forward_ctrl <= '0';
                    when "1001110" => forward_ctrl <= '0';
                    when "1001111" => forward_ctrl <= '0';
                    when "1010001" => forward_ctrl <= '0';
                    when "1011110" => forward_ctrl <= '0';
                    when "1011111" => forward_ctrl <= '0';
                    when "1100000" => forward_ctrl <= '0';
                    when "1100001" => forward_ctrl <= '1';
                    when "1100010" => forward_ctrl <= '0';
                    when "1101010" => forward_ctrl <= '1';
                    when "1101011" => forward_ctrl <= '0';
                    when "1101100" => forward_ctrl <= '1';
                    when "1101101" => forward_ctrl <= '1';
                    when "1101110" => forward_ctrl <= '1';
                    when others => forward_ctrl <= '-';
                end case;
                if forward_ctrl = '1' then
                    p_0_out_internal <= p_0_in_internal;
                else
                    p_0_out_internal <= read_port_0;
                end if;
            end if;
        end if;
    end process output_reg_proc;

    --
    -- Memory write address generation
    --
    mem_write_address_proc: process(schedule_cnt)
    begin
            case schedule_cnt is
                -- MemoryVariable(17, <b_asic.port.OutputPort object at 0x7f39890bb850>, {<b_asic.port.InputPort object at 0x7f399739b620>: 3, <b_asic.port.InputPort object at 0x7f39973a48a0>: 1}, 'mul0.0')
                when "0010000" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(18, <b_asic.port.OutputPort object at 0x7f39890bba10>, {<b_asic.port.InputPort object at 0x7f3997399be0>: 32, <b_asic.port.InputPort object at 0x7f39973a4130>: 3, <b_asic.port.InputPort object at 0x7f39973a54e0>: 1}, 'mul1.0')
                when "0010001" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(19, <b_asic.port.OutputPort object at 0x7f39890bbbd0>, {<b_asic.port.InputPort object at 0x7f399739a820>: 32, <b_asic.port.InputPort object at 0x7f399739b3f0>: 3}, 'mul2.0')
                when "0010010" =>
                    write_adr_0_0_0 <= to_unsigned(2, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(27, <b_asic.port.OutputPort object at 0x7f39973a4440>, {<b_asic.port.InputPort object at 0x7f3997398c20>: 12, <b_asic.port.InputPort object at 0x7f39973a4520>: 16}, 'addsub21.0')
                when "0011010" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(28, <b_asic.port.OutputPort object at 0x7f39973a5390>, {<b_asic.port.InputPort object at 0x7f3997386ba0>: 19}, 'addsub23.0')
                when "0011011" =>
                    write_adr_0_0_0 <= to_unsigned(3, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(29, <b_asic.port.OutputPort object at 0x7f399739ac10>, {<b_asic.port.InputPort object at 0x7f3997398de0>: 11, <b_asic.port.InputPort object at 0x7f399739acf0>: 16, <b_asic.port.InputPort object at 0x7f399739b770>: 15}, 'addsub16.0')
                when "0011100" =>
                    write_adr_0_0_0 <= to_unsigned(4, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(30, <b_asic.port.OutputPort object at 0x7f399739bc40>, {<b_asic.port.InputPort object at 0x7f399739b9a0>: 18}, 'addsub20.0')
                when "0011101" =>
                    write_adr_0_0_0 <= to_unsigned(5, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(31, <b_asic.port.OutputPort object at 0x7f399739b230>, {<b_asic.port.InputPort object at 0x7f399739af90>: 18}, 'addsub18.0')
                when "0011110" =>
                    write_adr_0_0_0 <= to_unsigned(6, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(46, <b_asic.port.OutputPort object at 0x7f3997399240>, {<b_asic.port.InputPort object at 0x7f3997399470>: 32}, 'mul30.0')
                when "0101101" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(53, <b_asic.port.OutputPort object at 0x7f399739ba80>, {<b_asic.port.InputPort object at 0x7f3997386350>: 12, <b_asic.port.InputPort object at 0x7f399739bd90>: 16}, 'addsub19.0')
                when "0110100" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(54, <b_asic.port.OutputPort object at 0x7f399739b070>, {<b_asic.port.InputPort object at 0x7f3997385390>: 19}, 'addsub17.0')
                when "0110101" =>
                    write_adr_0_0_0 <= to_unsigned(2, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(56, <b_asic.port.OutputPort object at 0x7f399739a900>, {<b_asic.port.InputPort object at 0x7f3997384ad0>: 18}, 'addsub15.0')
                when "0110111" =>
                    write_adr_0_0_0 <= to_unsigned(3, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1000000" =>
                    write_adr_0_0_0 <= to_unsigned(4, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(69, <b_asic.port.OutputPort object at 0x7f3997386430>, {<b_asic.port.InputPort object at 0x7f3997399da0>: 1, <b_asic.port.InputPort object at 0x7f39973a4c90>: 2}, 'mul17.0')
                when "1000100" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(70, <b_asic.port.OutputPort object at 0x7f3997386eb0>, {<b_asic.port.InputPort object at 0x7f3997384280>: 2}, 'mul19.0')
                when "1000101" =>
                    write_adr_0_0_0 <= to_unsigned(5, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(79, <b_asic.port.OutputPort object at 0x7f39973873f0>, {<b_asic.port.InputPort object at 0x7f39973a5010>: 24}, 'mul22.0')
                when "1001110" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(80, <b_asic.port.OutputPort object at 0x7f39973875b0>, {<b_asic.port.InputPort object at 0x7f39973877e0>: 25}, 'mul23.0')
                when "1001111" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(82, <b_asic.port.OutputPort object at 0x7f3997398590>, {<b_asic.port.InputPort object at 0x7f39973982f0>: 24}, 'addsub10.0')
                when "1010001" =>
                    write_adr_0_0_0 <= to_unsigned(2, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(95, <b_asic.port.OutputPort object at 0x7f39973848a0>, {<b_asic.port.InputPort object at 0x7f3997384600>: 2}, 'mul6.0')
                when "1011110" =>
                    write_adr_0_0_0 <= to_unsigned(3, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(96, <b_asic.port.OutputPort object at 0x7f39973856a0>, {<b_asic.port.InputPort object at 0x7f3997384d00>: 2}, 'mul10.0')
                when "1011111" =>
                    write_adr_0_0_0 <= to_unsigned(5, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(97, <b_asic.port.OutputPort object at 0x7f3997385860>, {<b_asic.port.InputPort object at 0x7f3997398050>: 5}, 'mul11.0')
                when "1100000" =>
                    write_adr_0_0_0 <= to_unsigned(3, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(98, <b_asic.port.OutputPort object at 0x7f3997385a20>, {<b_asic.port.InputPort object at 0x7f3997384ec0>: 1}, 'mul12.0')
                when "1100001" =>
                    write_adr_0_0_0 <= to_unsigned(5, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(99, <b_asic.port.OutputPort object at 0x7f3997385be0>, {<b_asic.port.InputPort object at 0x7f39973879a0>: 2}, 'mul13.0')
                when "1100010" =>
                    write_adr_0_0_0 <= to_unsigned(5, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(107, <b_asic.port.OutputPort object at 0x7f39973998d0>, {<b_asic.port.InputPort object at 0x7f39890bae40>: 1}, 'addsub13.0')
                when "1101010" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(108, <b_asic.port.OutputPort object at 0x7f39973a50f0>, {<b_asic.port.InputPort object at 0x7f39890bb000>: 5}, 'addsub22.0')
                when "1101011" =>
                    write_adr_0_0_0 <= to_unsigned(0, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(109, <b_asic.port.OutputPort object at 0x7f3997386970>, {<b_asic.port.InputPort object at 0x7f39890bb1c0>: 1}, 'addsub5.0')
                when "1101100" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(110, <b_asic.port.OutputPort object at 0x7f39973878c0>, {<b_asic.port.InputPort object at 0x7f39890bb0e0>: 1}, 'addsub7.0')
                when "1101101" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                -- MemoryVariable(111, <b_asic.port.OutputPort object at 0x7f39973983d0>, {<b_asic.port.InputPort object at 0x7f39890baf20>: 1}, 'addsub9.0')
                when "1101110" =>
                    write_adr_0_0_0 <= to_unsigned(1, write_adr_0_0_0'length);
                    write_en_0_0_0 <= '1';
                when others =>
                    write_adr_0_0_0 <= (others => '-');
                    write_en_0_0_0 <= '0';
            end case;
    end process mem_write_address_proc;


    --
    -- Memory read address generation
    --
    mem_read_address_proc: process(schedule_cnt)
    begin
            case schedule_cnt is
                -- MemoryVariable(17, <b_asic.port.OutputPort object at 0x7f39890bb850>, {<b_asic.port.InputPort object at 0x7f399739b620>: 3, <b_asic.port.InputPort object at 0x7f39973a48a0>: 1}, 'mul0.0')
                when "0010000" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(18, <b_asic.port.OutputPort object at 0x7f39890bba10>, {<b_asic.port.InputPort object at 0x7f3997399be0>: 32, <b_asic.port.InputPort object at 0x7f39973a4130>: 3, <b_asic.port.InputPort object at 0x7f39973a54e0>: 1}, 'mul1.0')
                when "0010001" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(17, <b_asic.port.OutputPort object at 0x7f39890bb850>, {<b_asic.port.InputPort object at 0x7f399739b620>: 3, <b_asic.port.InputPort object at 0x7f39973a48a0>: 1}, 'mul0.0')
                when "0010010" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(18, <b_asic.port.OutputPort object at 0x7f39890bba10>, {<b_asic.port.InputPort object at 0x7f3997399be0>: 32, <b_asic.port.InputPort object at 0x7f39973a4130>: 3, <b_asic.port.InputPort object at 0x7f39973a54e0>: 1}, 'mul1.0')
                when "0010011" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(19, <b_asic.port.OutputPort object at 0x7f39890bbbd0>, {<b_asic.port.InputPort object at 0x7f399739a820>: 32, <b_asic.port.InputPort object at 0x7f399739b3f0>: 3}, 'mul2.0')
                when "0010100" =>
                    read_adr_0_0_0 <= to_unsigned(2, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(27, <b_asic.port.OutputPort object at 0x7f39973a4440>, {<b_asic.port.InputPort object at 0x7f3997398c20>: 12, <b_asic.port.InputPort object at 0x7f39973a4520>: 16}, 'addsub21.0')
                when "0100101" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(29, <b_asic.port.OutputPort object at 0x7f399739ac10>, {<b_asic.port.InputPort object at 0x7f3997398de0>: 11, <b_asic.port.InputPort object at 0x7f399739acf0>: 16, <b_asic.port.InputPort object at 0x7f399739b770>: 15}, 'addsub16.0')
                when "0100110" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(27, <b_asic.port.OutputPort object at 0x7f39973a4440>, {<b_asic.port.InputPort object at 0x7f3997398c20>: 12, <b_asic.port.InputPort object at 0x7f39973a4520>: 16}, 'addsub21.0')
                when "0101001" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(29, <b_asic.port.OutputPort object at 0x7f399739ac10>, {<b_asic.port.InputPort object at 0x7f3997398de0>: 11, <b_asic.port.InputPort object at 0x7f399739acf0>: 16, <b_asic.port.InputPort object at 0x7f399739b770>: 15}, 'addsub16.0')
                when "0101010" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(29, <b_asic.port.OutputPort object at 0x7f399739ac10>, {<b_asic.port.InputPort object at 0x7f3997398de0>: 11, <b_asic.port.InputPort object at 0x7f399739acf0>: 16, <b_asic.port.InputPort object at 0x7f399739b770>: 15}, 'addsub16.0')
                when "0101011" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(28, <b_asic.port.OutputPort object at 0x7f39973a5390>, {<b_asic.port.InputPort object at 0x7f3997386ba0>: 19}, 'addsub23.0')
                when "0101101" =>
                    read_adr_0_0_0 <= to_unsigned(3, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(30, <b_asic.port.OutputPort object at 0x7f399739bc40>, {<b_asic.port.InputPort object at 0x7f399739b9a0>: 18}, 'addsub20.0')
                when "0101110" =>
                    read_adr_0_0_0 <= to_unsigned(5, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(31, <b_asic.port.OutputPort object at 0x7f399739b230>, {<b_asic.port.InputPort object at 0x7f399739af90>: 18}, 'addsub18.0')
                when "0101111" =>
                    read_adr_0_0_0 <= to_unsigned(6, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(18, <b_asic.port.OutputPort object at 0x7f39890bba10>, {<b_asic.port.InputPort object at 0x7f3997399be0>: 32, <b_asic.port.InputPort object at 0x7f39973a4130>: 3, <b_asic.port.InputPort object at 0x7f39973a54e0>: 1}, 'mul1.0')
                when "0110000" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(19, <b_asic.port.OutputPort object at 0x7f39890bbbd0>, {<b_asic.port.InputPort object at 0x7f399739a820>: 32, <b_asic.port.InputPort object at 0x7f399739b3f0>: 3}, 'mul2.0')
                when "0110001" =>
                    read_adr_0_0_0 <= to_unsigned(2, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(53, <b_asic.port.OutputPort object at 0x7f399739ba80>, {<b_asic.port.InputPort object at 0x7f3997386350>: 12, <b_asic.port.InputPort object at 0x7f399739bd90>: 16}, 'addsub19.0')
                when "0111111" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1000000" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1000001" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1000010" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(53, <b_asic.port.OutputPort object at 0x7f399739ba80>, {<b_asic.port.InputPort object at 0x7f3997386350>: 12, <b_asic.port.InputPort object at 0x7f399739bd90>: 16}, 'addsub19.0')
                when "1000011" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(69, <b_asic.port.OutputPort object at 0x7f3997386430>, {<b_asic.port.InputPort object at 0x7f3997399da0>: 1, <b_asic.port.InputPort object at 0x7f39973a4c90>: 2}, 'mul17.0')
                when "1000100" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(69, <b_asic.port.OutputPort object at 0x7f3997386430>, {<b_asic.port.InputPort object at 0x7f3997399da0>: 1, <b_asic.port.InputPort object at 0x7f39973a4c90>: 2}, 'mul17.0')
                when "1000101" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(70, <b_asic.port.OutputPort object at 0x7f3997386eb0>, {<b_asic.port.InputPort object at 0x7f3997384280>: 2}, 'mul19.0')
                when "1000110" =>
                    read_adr_0_0_0 <= to_unsigned(5, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(54, <b_asic.port.OutputPort object at 0x7f399739b070>, {<b_asic.port.InputPort object at 0x7f3997385390>: 19}, 'addsub17.0')
                when "1000111" =>
                    read_adr_0_0_0 <= to_unsigned(2, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(56, <b_asic.port.OutputPort object at 0x7f399739a900>, {<b_asic.port.InputPort object at 0x7f3997384ad0>: 18}, 'addsub15.0')
                when "1001000" =>
                    read_adr_0_0_0 <= to_unsigned(3, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1001001" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1001010" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(46, <b_asic.port.OutputPort object at 0x7f3997399240>, {<b_asic.port.InputPort object at 0x7f3997399470>: 32}, 'mul30.0')
                when "1001100" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(95, <b_asic.port.OutputPort object at 0x7f39973848a0>, {<b_asic.port.InputPort object at 0x7f3997384600>: 2}, 'mul6.0')
                when "1011111" =>
                    read_adr_0_0_0 <= to_unsigned(3, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(96, <b_asic.port.OutputPort object at 0x7f39973856a0>, {<b_asic.port.InputPort object at 0x7f3997384d00>: 2}, 'mul10.0')
                when "1100000" =>
                    read_adr_0_0_0 <= to_unsigned(5, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(98, <b_asic.port.OutputPort object at 0x7f3997385a20>, {<b_asic.port.InputPort object at 0x7f3997384ec0>: 1}, 'mul12.0')
                when "1100001" =>
                    read_adr_0_0_0 <= to_unsigned(5, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(99, <b_asic.port.OutputPort object at 0x7f3997385be0>, {<b_asic.port.InputPort object at 0x7f39973879a0>: 2}, 'mul13.0')
                when "1100011" =>
                    read_adr_0_0_0 <= to_unsigned(5, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(97, <b_asic.port.OutputPort object at 0x7f3997385860>, {<b_asic.port.InputPort object at 0x7f3997398050>: 5}, 'mul11.0')
                when "1100100" =>
                    read_adr_0_0_0 <= to_unsigned(3, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(79, <b_asic.port.OutputPort object at 0x7f39973873f0>, {<b_asic.port.InputPort object at 0x7f39973a5010>: 24}, 'mul22.0')
                when "1100101" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(65, <b_asic.port.OutputPort object at 0x7f3997386ac0>, {<b_asic.port.InputPort object at 0x7f3997386890>: 39, <b_asic.port.InputPort object at 0x7f3997386e40>: 1, <b_asic.port.InputPort object at 0x7f3997387000>: 2, <b_asic.port.InputPort object at 0x7f39973871c0>: 3, <b_asic.port.InputPort object at 0x7f3997387310>: 10, <b_asic.port.InputPort object at 0x7f39973874d0>: 11}, 'rec2.0')
                when "1100110" =>
                    read_adr_0_0_0 <= to_unsigned(4, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(80, <b_asic.port.OutputPort object at 0x7f39973875b0>, {<b_asic.port.InputPort object at 0x7f39973877e0>: 25}, 'mul23.0')
                when "1100111" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(82, <b_asic.port.OutputPort object at 0x7f3997398590>, {<b_asic.port.InputPort object at 0x7f39973982f0>: 24}, 'addsub10.0')
                when "1101000" =>
                    read_adr_0_0_0 <= to_unsigned(2, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(107, <b_asic.port.OutputPort object at 0x7f39973998d0>, {<b_asic.port.InputPort object at 0x7f39890bae40>: 1}, 'addsub13.0')
                when "1101010" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(109, <b_asic.port.OutputPort object at 0x7f3997386970>, {<b_asic.port.InputPort object at 0x7f39890bb1c0>: 1}, 'addsub5.0')
                when "1101100" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(110, <b_asic.port.OutputPort object at 0x7f39973878c0>, {<b_asic.port.InputPort object at 0x7f39890bb0e0>: 1}, 'addsub7.0')
                when "1101101" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(111, <b_asic.port.OutputPort object at 0x7f39973983d0>, {<b_asic.port.InputPort object at 0x7f39890baf20>: 1}, 'addsub9.0')
                when "1101110" =>
                    read_adr_0_0_0 <= to_unsigned(1, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                -- MemoryVariable(108, <b_asic.port.OutputPort object at 0x7f39973a50f0>, {<b_asic.port.InputPort object at 0x7f39890bb000>: 5}, 'addsub22.0')
                when "1101111" =>
                    read_adr_0_0_0 <= to_unsigned(0, read_adr_0_0_0'length);
                    read_en_0_0_0 <= '1';
                when others =>
                    read_adr_0_0_0 <= (others => '-');
                    read_en_0_0_0 <= '0';
            end case;
    end process mem_read_address_proc;

end architecture rtl;

