--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2026-06-05 16:09:11.439346)
-- B-ASIC version: 0.1.0.dev970+unknown.g621314118
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ldlt is
    port (
        clk : in std_logic;
        rst : in std_logic;
        in0_0_in : in std_logic_vector(31 downto 0);
        out0_0_out : out std_logic_vector(31 downto 0)
    );
end entity ldlt;

architecture rtl of ldlt is
    -- Component declaration
    component addsub0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_1_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component mul0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_1_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component in0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component neg0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component rec0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component out0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory1
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory2
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory3
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    -- addsub0 signals
    signal addsub0_0_in : std_logic_vector(31 downto 0);
    signal addsub0_1_in : std_logic_vector(31 downto 0);
    signal addsub0_0_out : std_logic_vector(31 downto 0);

    -- mul0 signals
    signal mul0_0_in : std_logic_vector(31 downto 0);
    signal mul0_1_in : std_logic_vector(31 downto 0);
    signal mul0_0_out : std_logic_vector(31 downto 0);

    -- in0 signals
    signal in0_0_out : std_logic_vector(31 downto 0);

    -- neg0 signals
    signal neg0_0_in : std_logic_vector(31 downto 0);
    signal neg0_0_out : std_logic_vector(31 downto 0);

    -- rec0 signals
    signal rec0_0_in : std_logic_vector(31 downto 0);
    signal rec0_0_out : std_logic_vector(31 downto 0);

    -- out0 signals
    signal out0_0_in : std_logic_vector(31 downto 0);

    -- memory0 signals
    signal memory0_0_in : std_logic_vector(31 downto 0);
    signal memory0_0_out : std_logic_vector(31 downto 0);

    -- memory1 signals
    signal memory1_0_in : std_logic_vector(31 downto 0);
    signal memory1_0_out : std_logic_vector(31 downto 0);

    -- memory2 signals
    signal memory2_0_in : std_logic_vector(31 downto 0);
    signal memory2_0_out : std_logic_vector(31 downto 0);

    -- memory3 signals
    signal memory3_0_in : std_logic_vector(31 downto 0);
    signal memory3_0_out : std_logic_vector(31 downto 0);

    signal schedule_cnt : unsigned(8 downto 0) := (others => '0');

    -- Internal signals for pipelined I/O
    signal in0_0_in_internal : std_logic_vector(31 downto 0);
    signal out0_0_out_internal : std_logic_vector(31 downto 0);

    -- Multiplexer control signals
    signal addsub0_0_sel : std_logic_vector(2 downto 0);
    signal addsub0_0_sel_next : std_logic_vector(2 downto 0);
    signal addsub0_1_sel : std_logic_vector(0 downto 0);
    signal addsub0_1_sel_next : std_logic_vector(0 downto 0);
    signal mul0_0_sel : std_logic_vector(2 downto 0);
    signal mul0_0_sel_next : std_logic_vector(2 downto 0);
    signal mul0_1_sel : std_logic_vector(2 downto 0);
    signal mul0_1_sel_next : std_logic_vector(2 downto 0);
    signal neg0_0_sel : std_logic_vector(0 downto 0);
    signal neg0_0_sel_next : std_logic_vector(0 downto 0);
    signal rec0_0_sel : std_logic_vector(0 downto 0);
    signal rec0_0_sel_next : std_logic_vector(0 downto 0);
    signal out0_0_sel : std_logic_vector(1 downto 0);
    signal out0_0_sel_next : std_logic_vector(1 downto 0);
    signal memory0_0_sel : std_logic_vector(0 downto 0);
    signal memory0_0_sel_next : std_logic_vector(0 downto 0);
    signal memory1_0_sel : std_logic_vector(1 downto 0);
    signal memory1_0_sel_next : std_logic_vector(1 downto 0);
    signal memory2_0_sel : std_logic_vector(0 downto 0);
    signal memory2_0_sel_next : std_logic_vector(0 downto 0);
    signal memory3_0_sel : std_logic_vector(0 downto 0);
    signal memory3_0_sel_next : std_logic_vector(0 downto 0);

begin
    -- Pipelining of I/O
    input_reg_proc: process(clk)
    begin
        if rising_edge(clk) then
            in0_0_in_internal <= in0_0_in;
        end if;
    end process input_reg_proc;

    output_reg_proc: process(clk)
    begin
        if rising_edge(clk) then
            out0_0_out <= out0_0_out_internal;
        end if;
    end process output_reg_proc;

    -- Component instantiation
    addsub0_inst: addsub0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => addsub0_0_in,
            p_1_in => addsub0_1_in,
            p_0_out => addsub0_0_out
        );

    mul0_inst: mul0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => mul0_0_in,
            p_1_in => mul0_1_in,
            p_0_out => mul0_0_out
        );

    in0_inst: in0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => in0_0_in_internal,
            p_0_out => in0_0_out
        );

    neg0_inst: neg0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => neg0_0_in,
            p_0_out => neg0_0_out
        );

    rec0_inst: rec0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => rec0_0_in,
            p_0_out => rec0_0_out
        );

    out0_inst: out0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => out0_0_in,
            p_0_out => out0_0_out_internal
        );

    memory0_inst: memory0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory0_0_in,
            p_0_out => memory0_0_out
        );

    memory1_inst: memory1
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory1_0_in,
            p_0_out => memory1_0_out
        );

    memory2_inst: memory2
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory2_0_in,
            p_0_out => memory2_0_out
        );

    memory3_inst: memory3
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory3_0_in,
            p_0_out => memory3_0_out
        );

    -- Schedule counter
    schedule_cnt_proc: process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                schedule_cnt <= (others => '0');
            else
                if schedule_cnt = 407 then
                    schedule_cnt <= (others => '0');
                else
                    schedule_cnt <= schedule_cnt + 1;
                end if;
            end if;
        end if;
    end process schedule_cnt_proc;

    -- Multiplexer control signal generation
    with schedule_cnt select
        addsub0_0_sel_next <=
            "011" when "000011110",
            "011" when "000011111",
            "011" when "000100000",
            "011" when "000100001",
            "011" when "000100010",
            "011" when "000100011",
            "011" when "000100100",
            "011" when "000100101",
            "011" when "000100110",
            "011" when "000100111",
            "011" when "000101000",
            "011" when "000101001",
            "011" when "000101010",
            "011" when "000101011",
            "100" when "000101100",
            "100" when "000101101",
            "011" when "000101110",
            "100" when "000101111",
            "100" when "000110000",
            "100" when "000110001",
            "100" when "000110010",
            "100" when "000110011",
            "011" when "000110100",
            "011" when "000110101",
            "011" when "000110110",
            "011" when "000110111",
            "011" when "000111000",
            "011" when "000111111",
            "011" when "001000110",
            "011" when "001000111",
            "011" when "001001000",
            "011" when "001001001",
            "011" when "001001010",
            "011" when "001001011",
            "011" when "001001100",
            "011" when "001001101",
            "011" when "001001110",
            "011" when "001001111",
            "011" when "001010000",
            "011" when "001010001",
            "011" when "001010010",
            "011" when "001010011",
            "011" when "001010100",
            "011" when "001010101",
            "011" when "001010110",
            "011" when "001010111",
            "011" when "001011000",
            "010" when "001011001",
            "011" when "001011010",
            "010" when "001011011",
            "010" when "001011100",
            "011" when "001011101",
            "010" when "001011110",
            "010" when "001011111",
            "010" when "001100000",
            "001" when "001100111",
            "011" when "001101110",
            "011" when "001101111",
            "011" when "001110000",
            "011" when "001110001",
            "011" when "001110010",
            "011" when "001110011",
            "011" when "001110100",
            "011" when "001110101",
            "011" when "001110110",
            "011" when "001110111",
            "011" when "001111000",
            "011" when "001111001",
            "011" when "001111010",
            "011" when "001111011",
            "011" when "001111100",
            "010" when "001111101",
            "011" when "001111110",
            "010" when "001111111",
            "011" when "010000000",
            "011" when "010000001",
            "001" when "010000010",
            "011" when "010000011",
            "001" when "010000100",
            "011" when "010000101",
            "010" when "010000110",
            "001" when "010001001",
            "011" when "010001101",
            "001" when "010001110",
            "011" when "010010110",
            "011" when "010010111",
            "011" when "010011000",
            "011" when "010011001",
            "011" when "010011010",
            "011" when "010011011",
            "011" when "010011100",
            "011" when "010011101",
            "011" when "010011110",
            "011" when "010011111",
            "001" when "010100000",
            "011" when "010100001",
            "011" when "010100010",
            "011" when "010100011",
            "001" when "010100100",
            "011" when "010100101",
            "011" when "010100110",
            "001" when "010100111",
            "011" when "010101000",
            "011" when "010101001",
            "011" when "010101010",
            "001" when "010101011",
            "011" when "010110000",
            "011" when "010110001",
            "010" when "010110010",
            "010" when "010110011",
            "100" when "010110100",
            "011" when "010110101",
            "011" when "010111110",
            "011" when "010111111",
            "011" when "011000000",
            "011" when "011000001",
            "011" when "011000010",
            "011" when "011000011",
            "011" when "011000100",
            "011" when "011000101",
            "011" when "011000110",
            "010" when "011000111",
            "011" when "011001000",
            "011" when "011001001",
            "011" when "011001010",
            "010" when "011001011",
            "011" when "011001100",
            "011" when "011001101",
            "011" when "011001110",
            "010" when "011001111",
            "011" when "011010111",
            "011" when "011011000",
            "010" when "011011010",
            "011" when "011011011",
            "011" when "011011100",
            "011" when "011011101",
            "011" when "011011110",
            "001" when "011011111",
            "010" when "011100010",
            "000" when "011100011",
            "011" when "011100110",
            "011" when "011100111",
            "011" when "011101000",
            "011" when "011101001",
            "011" when "011101010",
            "011" when "011101011",
            "010" when "011101100",
            "011" when "011101101",
            "011" when "011101110",
            "011" when "011101111",
            "011" when "011110000",
            "011" when "011110001",
            "001" when "011110010",
            "011" when "100000000",
            "011" when "100000001",
            "011" when "100000010",
            "011" when "100000011",
            "011" when "100000101",
            "011" when "100000111",
            "011" when "100001001",
            "000" when "100001010",
            "000" when "100001101",
            "011" when "100001110",
            "011" when "100001111",
            "011" when "100010000",
            "011" when "100010001",
            "011" when "100010010",
            "001" when "100010011",
            "011" when "100010100",
            "001" when "100010101",
            "011" when "100010110",
            "011" when "100010111",
            "011" when "100011000",
            "001" when "100011001",
            "001" when "100011010",
            "011" when "100110000",
            "011" when "100110001",
            "011" when "100110011",
            "011" when "100110100",
            "011" when "100110101",
            "011" when "100110110",
            "011" when "100110111",
            "000" when "100111001",
            "011" when "100111010",
            "011" when "100111100",
            "000" when "100111101",
            "011" when "100111110",
            "011" when "101000000",
            "011" when "101000001",
            "011" when "101000011",
            "000" when "101000100",
            "010" when "101000101",
            "000" when "101000110",
            "011" when "101000111",
            "011" when "101001000",
            "010" when "101001001",
            "011" when "101100110",
            "011" when "101101000",
            "011" when "101101001",
            "011" when "101101010",
            "011" when "101101011",
            "011" when "101101100",
            "000" when "101101101",
            "011" when "101110011",
            "010" when "101110100",
            "011" when "101110101",
            "011" when "101110110",
            "011" when "101110111",
            "011" when "101111000",
            "001" when "101111001",
            "011" when "101111010",
            "011" when "101111011",
            "011" when "101111100",
            "011" when "101111101",
            "010" when "101111110",
            "011" when "101111111",
            "011" when "110000000",
            "011" when "110000001",
            "011" when "110000010",
            "010" when "110000011",
            "011" when "110000100",
            "010" when "110000101",
            "011" when "110000110",
            "010" when "110000111",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            addsub0_0_sel <= addsub0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        addsub0_1_sel_next <=
            "0" when "000011110",
            "0" when "000011111",
            "0" when "000100000",
            "0" when "000100001",
            "0" when "000100010",
            "0" when "000100011",
            "0" when "000100100",
            "0" when "000100101",
            "0" when "000100110",
            "0" when "000100111",
            "0" when "000101000",
            "0" when "000101001",
            "0" when "000101010",
            "0" when "000101011",
            "0" when "000101100",
            "0" when "000101101",
            "0" when "000101110",
            "0" when "000101111",
            "0" when "000110000",
            "0" when "000110001",
            "0" when "000110010",
            "0" when "000110011",
            "0" when "000110100",
            "0" when "000110101",
            "0" when "000110110",
            "0" when "000110111",
            "0" when "000111000",
            "0" when "000111111",
            "0" when "001000110",
            "0" when "001000111",
            "0" when "001001000",
            "0" when "001001001",
            "0" when "001001010",
            "0" when "001001011",
            "0" when "001001100",
            "0" when "001001101",
            "0" when "001001110",
            "0" when "001001111",
            "0" when "001010000",
            "0" when "001010001",
            "0" when "001010010",
            "0" when "001010011",
            "0" when "001010100",
            "0" when "001010101",
            "0" when "001010110",
            "0" when "001010111",
            "0" when "001011000",
            "0" when "001011001",
            "0" when "001011010",
            "0" when "001011011",
            "0" when "001011100",
            "0" when "001011101",
            "0" when "001011110",
            "0" when "001011111",
            "0" when "001100000",
            "0" when "001100111",
            "0" when "001101110",
            "0" when "001101111",
            "0" when "001110000",
            "0" when "001110001",
            "0" when "001110010",
            "0" when "001110011",
            "0" when "001110100",
            "0" when "001110101",
            "0" when "001110110",
            "0" when "001110111",
            "0" when "001111000",
            "0" when "001111001",
            "0" when "001111010",
            "0" when "001111011",
            "0" when "001111100",
            "0" when "001111101",
            "0" when "001111110",
            "0" when "001111111",
            "0" when "010000000",
            "0" when "010000001",
            "0" when "010000010",
            "0" when "010000011",
            "0" when "010000100",
            "0" when "010000101",
            "0" when "010000110",
            "0" when "010001001",
            "0" when "010001101",
            "0" when "010001110",
            "0" when "010010110",
            "0" when "010010111",
            "0" when "010011000",
            "0" when "010011001",
            "0" when "010011010",
            "0" when "010011011",
            "0" when "010011100",
            "0" when "010011101",
            "0" when "010011110",
            "0" when "010011111",
            "0" when "010100000",
            "0" when "010100001",
            "0" when "010100010",
            "0" when "010100011",
            "0" when "010100100",
            "0" when "010100101",
            "0" when "010100110",
            "0" when "010100111",
            "0" when "010101000",
            "0" when "010101001",
            "0" when "010101010",
            "0" when "010101011",
            "0" when "010110000",
            "0" when "010110001",
            "0" when "010110010",
            "0" when "010110011",
            "0" when "010110100",
            "0" when "010110101",
            "0" when "010111110",
            "0" when "010111111",
            "0" when "011000000",
            "0" when "011000001",
            "0" when "011000010",
            "0" when "011000011",
            "0" when "011000100",
            "0" when "011000101",
            "0" when "011000110",
            "0" when "011000111",
            "0" when "011001000",
            "0" when "011001001",
            "0" when "011001010",
            "0" when "011001011",
            "0" when "011001100",
            "0" when "011001101",
            "0" when "011001110",
            "0" when "011001111",
            "0" when "011010111",
            "0" when "011011000",
            "0" when "011011010",
            "0" when "011011011",
            "0" when "011011100",
            "0" when "011011101",
            "0" when "011011110",
            "0" when "011011111",
            "0" when "011100010",
            "1" when "011100011",
            "0" when "011100110",
            "0" when "011100111",
            "0" when "011101000",
            "0" when "011101001",
            "0" when "011101010",
            "0" when "011101011",
            "0" when "011101100",
            "0" when "011101101",
            "0" when "011101110",
            "0" when "011101111",
            "0" when "011110000",
            "0" when "011110001",
            "0" when "011110010",
            "0" when "100000000",
            "0" when "100000001",
            "0" when "100000010",
            "0" when "100000011",
            "0" when "100000101",
            "0" when "100000111",
            "0" when "100001001",
            "1" when "100001010",
            "1" when "100001101",
            "0" when "100001110",
            "0" when "100001111",
            "0" when "100010000",
            "0" when "100010001",
            "0" when "100010010",
            "0" when "100010011",
            "0" when "100010100",
            "0" when "100010101",
            "0" when "100010110",
            "0" when "100010111",
            "0" when "100011000",
            "0" when "100011001",
            "0" when "100011010",
            "0" when "100110000",
            "0" when "100110001",
            "0" when "100110011",
            "0" when "100110100",
            "0" when "100110101",
            "0" when "100110110",
            "0" when "100110111",
            "1" when "100111001",
            "0" when "100111010",
            "0" when "100111100",
            "1" when "100111101",
            "0" when "100111110",
            "0" when "101000000",
            "0" when "101000001",
            "0" when "101000011",
            "1" when "101000100",
            "0" when "101000101",
            "1" when "101000110",
            "0" when "101000111",
            "0" when "101001000",
            "0" when "101001001",
            "0" when "101100110",
            "0" when "101101000",
            "0" when "101101001",
            "0" when "101101010",
            "0" when "101101011",
            "0" when "101101100",
            "1" when "101101101",
            "0" when "101110011",
            "0" when "101110100",
            "0" when "101110101",
            "0" when "101110110",
            "0" when "101110111",
            "0" when "101111000",
            "0" when "101111001",
            "0" when "101111010",
            "0" when "101111011",
            "0" when "101111100",
            "0" when "101111101",
            "0" when "101111110",
            "0" when "101111111",
            "0" when "110000000",
            "0" when "110000001",
            "0" when "110000010",
            "0" when "110000011",
            "0" when "110000100",
            "0" when "110000101",
            "0" when "110000110",
            "0" when "110000111",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            addsub0_1_sel <= addsub0_1_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mul0_0_sel_next <=
            "100" when "000010010",
            "010" when "000010011",
            "100" when "000010100",
            "100" when "000010101",
            "100" when "000010110",
            "100" when "000010111",
            "100" when "000011000",
            "010" when "000011001",
            "010" when "000011010",
            "100" when "000011011",
            "100" when "000011100",
            "100" when "000011101",
            "100" when "000011110",
            "100" when "000011111",
            "100" when "000100000",
            "100" when "000100001",
            "100" when "000100010",
            "100" when "000100011",
            "100" when "000100100",
            "100" when "000100101",
            "100" when "000100110",
            "100" when "000100111",
            "100" when "000101000",
            "100" when "000101001",
            "100" when "000101010",
            "100" when "000101011",
            "010" when "000101100",
            "010" when "000101101",
            "100" when "000101110",
            "010" when "000101111",
            "010" when "000110000",
            "010" when "000110001",
            "010" when "000110010",
            "010" when "000110011",
            "010" when "000111001",
            "100" when "000111010",
            "100" when "000111011",
            "100" when "000111100",
            "100" when "000111101",
            "100" when "000111110",
            "100" when "000111111",
            "100" when "001000000",
            "100" when "001000001",
            "100" when "001000010",
            "100" when "001000011",
            "100" when "001000100",
            "100" when "001000101",
            "100" when "001000110",
            "100" when "001000111",
            "100" when "001001000",
            "100" when "001001001",
            "100" when "001001010",
            "100" when "001001011",
            "100" when "001001100",
            "100" when "001001101",
            "100" when "001001110",
            "100" when "001001111",
            "100" when "001010000",
            "100" when "001010001",
            "100" when "001010010",
            "011" when "001010011",
            "100" when "001010100",
            "011" when "001010101",
            "011" when "001010110",
            "100" when "001010111",
            "001" when "001011000",
            "001" when "001011001",
            "011" when "001011010",
            "100" when "001011011",
            "001" when "001011100",
            "000" when "001100001",
            "100" when "001100010",
            "100" when "001100011",
            "100" when "001100100",
            "100" when "001100101",
            "100" when "001100110",
            "100" when "001100111",
            "100" when "001101000",
            "100" when "001101001",
            "100" when "001101010",
            "100" when "001101011",
            "100" when "001101100",
            "100" when "001101101",
            "100" when "001101110",
            "100" when "001101111",
            "100" when "001110000",
            "100" when "001110001",
            "100" when "001110010",
            "100" when "001110011",
            "100" when "001110100",
            "100" when "001110101",
            "011" when "001110110",
            "011" when "001110111",
            "001" when "001111000",
            "001" when "001111001",
            "100" when "001111010",
            "001" when "001111011",
            "001" when "001111100",
            "001" when "001111101",
            "001" when "001111110",
            "001" when "001111111",
            "001" when "010000000",
            "100" when "010000001",
            "100" when "010000010",
            "011" when "010000011",
            "011" when "010000100",
            "011" when "010000101",
            "000" when "010000111",
            "000" when "010001000",
            "100" when "010001010",
            "100" when "010001011",
            "100" when "010001100",
            "100" when "010001101",
            "100" when "010001110",
            "100" when "010001111",
            "100" when "010010000",
            "100" when "010010001",
            "100" when "010010010",
            "100" when "010010011",
            "100" when "010010100",
            "100" when "010010101",
            "100" when "010010110",
            "100" when "010010111",
            "100" when "010011000",
            "011" when "010011001",
            "011" when "010011010",
            "011" when "010011011",
            "100" when "010011100",
            "011" when "010011101",
            "011" when "010011110",
            "011" when "010011111",
            "011" when "010100000",
            "011" when "010100001",
            "011" when "010100010",
            "011" when "010100011",
            "011" when "010100100",
            "011" when "010100101",
            "100" when "010100110",
            "100" when "010100111",
            "100" when "010101000",
            "100" when "010101001",
            "011" when "010101010",
            "011" when "010101011",
            "000" when "010101100",
            "000" when "010101101",
            "000" when "010101110",
            "000" when "010101111",
            "011" when "010110000",
            "011" when "010110001",
            "100" when "010110010",
            "100" when "010110011",
            "010" when "010110100",
            "100" when "010110101",
            "100" when "010110110",
            "100" when "010110111",
            "100" when "010111000",
            "100" when "010111001",
            "100" when "010111010",
            "010" when "010111011",
            "010" when "010111100",
            "010" when "010111101",
            "011" when "010111110",
            "011" when "010111111",
            "011" when "011000000",
            "011" when "011000001",
            "011" when "011000010",
            "011" when "011000011",
            "011" when "011000100",
            "011" when "011000101",
            "001" when "011000110",
            "001" when "011000111",
            "001" when "011001000",
            "001" when "011001001",
            "100" when "011001010",
            "100" when "011001011",
            "100" when "011001100",
            "100" when "011001101",
            "100" when "011001110",
            "100" when "011001111",
            "100" when "011010000",
            "011" when "011010001",
            "011" when "011010010",
            "011" when "011010011",
            "011" when "011010100",
            "011" when "011010101",
            "000" when "011010110",
            "011" when "011010111",
            "011" when "011011000",
            "011" when "011011001",
            "100" when "011011010",
            "100" when "011011011",
            "011" when "011011100",
            "011" when "011011101",
            "100" when "011011110",
            "100" when "011011111",
            "100" when "011100000",
            "100" when "011100001",
            "100" when "011100010",
            "001" when "011100011",
            "001" when "011100100",
            "001" when "011100101",
            "001" when "011100110",
            "001" when "011100111",
            "001" when "011101000",
            "001" when "011101001",
            "001" when "011101010",
            "001" when "011101011",
            "001" when "011101100",
            "100" when "011101101",
            "100" when "011101110",
            "100" when "011101111",
            "100" when "011110000",
            "100" when "011110001",
            "100" when "011110010",
            "100" when "011110011",
            "100" when "011110100",
            "100" when "011110101",
            "100" when "011110110",
            "100" when "011110111",
            "100" when "011111000",
            "100" when "011111001",
            "011" when "011111010",
            "011" when "011111011",
            "011" when "011111100",
            "011" when "011111101",
            "000" when "011111110",
            "011" when "011111111",
            "011" when "100000000",
            "011" when "100000001",
            "100" when "100000010",
            "011" when "100000011",
            "001" when "100000100",
            "001" when "100000101",
            "001" when "100000110",
            "001" when "100000111",
            "100" when "100001000",
            "001" when "100001001",
            "001" when "100001010",
            "001" when "100001011",
            "001" when "100001100",
            "001" when "100001101",
            "001" when "100001110",
            "011" when "100001111",
            "011" when "100010000",
            "011" when "100010001",
            "011" when "100010010",
            "011" when "100010011",
            "011" when "100010100",
            "100" when "100010101",
            "100" when "100010110",
            "100" when "100010111",
            "100" when "100011000",
            "100" when "100011001",
            "100" when "100011010",
            "100" when "100011011",
            "100" when "100011100",
            "100" when "100011101",
            "100" when "100011110",
            "100" when "100011111",
            "100" when "100100000",
            "100" when "100100001",
            "100" when "100100010",
            "100" when "100100011",
            "100" when "100100100",
            "100" when "100100101",
            "100" when "100100110",
            "100" when "100100111",
            "100" when "100101000",
            "100" when "100101001",
            "011" when "100101010",
            "011" when "100101011",
            "011" when "100101100",
            "011" when "100101101",
            "011" when "100101110",
            "011" when "100101111",
            "011" when "100110000",
            "011" when "100110001",
            "011" when "100110010",
            "011" when "100110011",
            "011" when "100110100",
            "011" when "100110101",
            "011" when "100110110",
            "011" when "100110111",
            "011" when "100111000",
            "001" when "100111001",
            "011" when "100111010",
            "011" when "100111011",
            "011" when "100111100",
            "001" when "100111101",
            "011" when "100111110",
            "011" when "100111111",
            "011" when "101000000",
            "011" when "101000001",
            "011" when "101000010",
            "011" when "101000011",
            "100" when "101000100",
            "100" when "101000101",
            "100" when "101000110",
            "100" when "101000111",
            "100" when "101001000",
            "100" when "101001001",
            "100" when "101001010",
            "100" when "101001011",
            "100" when "101001100",
            "100" when "101001101",
            "100" when "101001110",
            "100" when "101001111",
            "100" when "101010000",
            "100" when "101010001",
            "100" when "101010010",
            "100" when "101010011",
            "100" when "101010100",
            "100" when "101010101",
            "100" when "101010110",
            "100" when "101010111",
            "100" when "101011000",
            "100" when "101011001",
            "100" when "101011010",
            "100" when "101011011",
            "100" when "101011100",
            "100" when "101011101",
            "100" when "101011110",
            "100" when "101011111",
            "011" when "101100000",
            "011" when "101100001",
            "011" when "101100010",
            "011" when "101100011",
            "011" when "101100100",
            "000" when "101100101",
            "011" when "101100110",
            "011" when "101100111",
            "011" when "101101000",
            "011" when "101101001",
            "011" when "101101010",
            "011" when "101101011",
            "011" when "101101100",
            "001" when "101101101",
            "011" when "101101110",
            "011" when "101101111",
            "011" when "101110000",
            "011" when "101110001",
            "011" when "101110010",
            "011" when "101110011",
            "001" when "101110100",
            "011" when "101110101",
            "011" when "101110110",
            "011" when "101110111",
            "011" when "101111000",
            "011" when "101111001",
            "011" when "101111010",
            "011" when "101111011",
            "011" when "101111100",
            "011" when "101111101",
            "001" when "101111110",
            "011" when "101111111",
            "011" when "110000000",
            "011" when "110000001",
            "001" when "110000010",
            "001" when "110000011",
            "001" when "110000100",
            "001" when "110000101",
            "001" when "110000110",
            "001" when "110000111",
            "001" when "110001000",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mul0_0_sel <= mul0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mul0_1_sel_next <=
            "010" when "000010010",
            "001" when "000010011",
            "001" when "000010100",
            "001" when "000010101",
            "001" when "000010110",
            "001" when "000010111",
            "000" when "000011000",
            "011" when "000011001",
            "011" when "000011010",
            "011" when "000011011",
            "011" when "000011100",
            "011" when "000011101",
            "011" when "000011110",
            "011" when "000011111",
            "011" when "000100000",
            "011" when "000100001",
            "011" when "000100010",
            "011" when "000100011",
            "011" when "000100100",
            "011" when "000100101",
            "011" when "000100110",
            "011" when "000100111",
            "011" when "000101000",
            "011" when "000101001",
            "011" when "000101010",
            "011" when "000101011",
            "011" when "000101100",
            "011" when "000101101",
            "011" when "000101110",
            "011" when "000101111",
            "011" when "000110000",
            "011" when "000110001",
            "011" when "000110010",
            "001" when "000110011",
            "000" when "000111001",
            "010" when "000111010",
            "001" when "000111011",
            "001" when "000111100",
            "001" when "000111101",
            "001" when "000111110",
            "001" when "000111111",
            "000" when "001000000",
            "011" when "001000001",
            "011" when "001000010",
            "011" when "001000011",
            "011" when "001000100",
            "011" when "001000101",
            "011" when "001000110",
            "011" when "001000111",
            "011" when "001001000",
            "001" when "001001001",
            "011" when "001001010",
            "011" when "001001011",
            "011" when "001001100",
            "001" when "001001101",
            "011" when "001001110",
            "001" when "001001111",
            "011" when "001010000",
            "011" when "001010001",
            "001" when "001010010",
            "100" when "001010011",
            "001" when "001010100",
            "100" when "001010101",
            "100" when "001010110",
            "011" when "001010111",
            "100" when "001011000",
            "100" when "001011001",
            "100" when "001011010",
            "001" when "001011011",
            "100" when "001011100",
            "100" when "001100001",
            "010" when "001100010",
            "011" when "001100011",
            "011" when "001100100",
            "011" when "001100101",
            "011" when "001100110",
            "011" when "001100111",
            "000" when "001101000",
            "011" when "001101001",
            "001" when "001101010",
            "011" when "001101011",
            "001" when "001101100",
            "001" when "001101101",
            "011" when "001101110",
            "001" when "001101111",
            "001" when "001110000",
            "001" when "001110001",
            "011" when "001110010",
            "001" when "001110011",
            "001" when "001110100",
            "001" when "001110101",
            "100" when "001110110",
            "100" when "001110111",
            "100" when "001111000",
            "100" when "001111001",
            "001" when "001111010",
            "100" when "001111011",
            "100" when "001111100",
            "100" when "001111101",
            "100" when "001111110",
            "100" when "001111111",
            "100" when "010000000",
            "011" when "010000001",
            "011" when "010000010",
            "100" when "010000011",
            "100" when "010000100",
            "100" when "010000101",
            "100" when "010000111",
            "100" when "010001000",
            "010" when "010001010",
            "011" when "010001011",
            "011" when "010001100",
            "011" when "010001101",
            "011" when "010001110",
            "011" when "010001111",
            "000" when "010010000",
            "011" when "010010001",
            "011" when "010010010",
            "011" when "010010011",
            "011" when "010010100",
            "011" when "010010101",
            "011" when "010010110",
            "011" when "010010111",
            "011" when "010011000",
            "100" when "010011001",
            "100" when "010011010",
            "100" when "010011011",
            "011" when "010011100",
            "100" when "010011101",
            "100" when "010011110",
            "100" when "010011111",
            "100" when "010100000",
            "100" when "010100001",
            "100" when "010100010",
            "100" when "010100011",
            "100" when "010100100",
            "100" when "010100101",
            "011" when "010100110",
            "011" when "010100111",
            "011" when "010101000",
            "011" when "010101001",
            "100" when "010101010",
            "100" when "010101011",
            "100" when "010101100",
            "100" when "010101101",
            "100" when "010101110",
            "100" when "010101111",
            "100" when "010110000",
            "100" when "010110001",
            "010" when "010110010",
            "001" when "010110011",
            "001" when "010110100",
            "001" when "010110101",
            "001" when "010110110",
            "001" when "010110111",
            "000" when "010111000",
            "011" when "010111001",
            "011" when "010111010",
            "011" when "010111011",
            "011" when "010111100",
            "001" when "010111101",
            "100" when "010111110",
            "100" when "010111111",
            "100" when "011000000",
            "100" when "011000001",
            "100" when "011000010",
            "100" when "011000011",
            "100" when "011000100",
            "100" when "011000101",
            "100" when "011000110",
            "100" when "011000111",
            "100" when "011001000",
            "100" when "011001001",
            "001" when "011001010",
            "001" when "011001011",
            "001" when "011001100",
            "001" when "011001101",
            "001" when "011001110",
            "001" when "011001111",
            "001" when "011010000",
            "100" when "011010001",
            "100" when "011010010",
            "100" when "011010011",
            "100" when "011010100",
            "100" when "011010101",
            "100" when "011010110",
            "100" when "011010111",
            "100" when "011011000",
            "100" when "011011001",
            "010" when "011011010",
            "011" when "011011011",
            "100" when "011011100",
            "100" when "011011101",
            "011" when "011011110",
            "011" when "011011111",
            "000" when "011100000",
            "001" when "011100001",
            "001" when "011100010",
            "100" when "011100011",
            "100" when "011100100",
            "100" when "011100101",
            "100" when "011100110",
            "100" when "011100111",
            "100" when "011101000",
            "100" when "011101001",
            "100" when "011101010",
            "100" when "011101011",
            "100" when "011101100",
            "011" when "011101101",
            "011" when "011101110",
            "011" when "011101111",
            "011" when "011110000",
            "011" when "011110001",
            "011" when "011110010",
            "011" when "011110011",
            "011" when "011110100",
            "011" when "011110101",
            "011" when "011110110",
            "011" when "011110111",
            "011" when "011111000",
            "011" when "011111001",
            "100" when "011111010",
            "100" when "011111011",
            "100" when "011111100",
            "100" when "011111101",
            "100" when "011111110",
            "100" when "011111111",
            "100" when "100000000",
            "100" when "100000001",
            "010" when "100000010",
            "100" when "100000011",
            "100" when "100000100",
            "100" when "100000101",
            "100" when "100000110",
            "100" when "100000111",
            "000" when "100001000",
            "100" when "100001001",
            "100" when "100001010",
            "100" when "100001011",
            "100" when "100001100",
            "100" when "100001101",
            "100" when "100001110",
            "100" when "100001111",
            "100" when "100010000",
            "100" when "100010001",
            "100" when "100010010",
            "100" when "100010011",
            "100" when "100010100",
            "011" when "100010101",
            "011" when "100010110",
            "011" when "100010111",
            "011" when "100011000",
            "011" when "100011001",
            "011" when "100011010",
            "011" when "100011011",
            "011" when "100011100",
            "011" when "100011101",
            "011" when "100011110",
            "011" when "100011111",
            "011" when "100100000",
            "011" when "100100001",
            "011" when "100100010",
            "011" when "100100011",
            "011" when "100100100",
            "011" when "100100101",
            "011" when "100100110",
            "011" when "100100111",
            "011" when "100101000",
            "011" when "100101001",
            "100" when "100101010",
            "100" when "100101011",
            "100" when "100101100",
            "100" when "100101101",
            "100" when "100101110",
            "100" when "100101111",
            "100" when "100110000",
            "100" when "100110001",
            "100" when "100110010",
            "100" when "100110011",
            "100" when "100110100",
            "100" when "100110101",
            "100" when "100110110",
            "100" when "100110111",
            "100" when "100111000",
            "100" when "100111001",
            "100" when "100111010",
            "100" when "100111011",
            "100" when "100111100",
            "100" when "100111101",
            "100" when "100111110",
            "100" when "100111111",
            "100" when "101000000",
            "100" when "101000001",
            "100" when "101000010",
            "100" when "101000011",
            "001" when "101000100",
            "001" when "101000101",
            "001" when "101000110",
            "001" when "101000111",
            "001" when "101001000",
            "001" when "101001001",
            "001" when "101001010",
            "001" when "101001011",
            "001" when "101001100",
            "001" when "101001101",
            "001" when "101001110",
            "001" when "101001111",
            "001" when "101010000",
            "001" when "101010001",
            "001" when "101010010",
            "001" when "101010011",
            "001" when "101010100",
            "001" when "101010101",
            "001" when "101010110",
            "001" when "101010111",
            "001" when "101011000",
            "001" when "101011001",
            "001" when "101011010",
            "001" when "101011011",
            "001" when "101011100",
            "001" when "101011101",
            "001" when "101011110",
            "001" when "101011111",
            "100" when "101100000",
            "100" when "101100001",
            "100" when "101100010",
            "100" when "101100011",
            "100" when "101100100",
            "100" when "101100101",
            "100" when "101100110",
            "100" when "101100111",
            "100" when "101101000",
            "100" when "101101001",
            "100" when "101101010",
            "100" when "101101011",
            "100" when "101101100",
            "100" when "101101101",
            "100" when "101101110",
            "100" when "101101111",
            "100" when "101110000",
            "100" when "101110001",
            "100" when "101110010",
            "100" when "101110011",
            "100" when "101110100",
            "100" when "101110101",
            "100" when "101110110",
            "100" when "101110111",
            "100" when "101111000",
            "100" when "101111001",
            "100" when "101111010",
            "100" when "101111011",
            "100" when "101111100",
            "100" when "101111101",
            "100" when "101111110",
            "100" when "101111111",
            "100" when "110000000",
            "100" when "110000001",
            "100" when "110000010",
            "100" when "110000011",
            "100" when "110000100",
            "100" when "110000101",
            "100" when "110000110",
            "100" when "110000111",
            "100" when "110001000",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mul0_1_sel <= mul0_1_sel_next;
        end if;
    end process;

    with schedule_cnt select
        neg0_0_sel_next <=
            "0" when "000011000",
            "0" when "001000000",
            "1" when "001100010",
            "0" when "001101000",
            "1" when "010000101",
            "1" when "010000110",
            "0" when "010010000",
            "1" when "010101000",
            "1" when "010101001",
            "1" when "010101010",
            "0" when "010111000",
            "1" when "011001101",
            "1" when "011001110",
            "1" when "011001111",
            "1" when "011010000",
            "0" when "011100000",
            "1" when "011110010",
            "1" when "011110011",
            "1" when "011110100",
            "1" when "011110101",
            "1" when "011110110",
            "0" when "100001000",
            "1" when "100011000",
            "1" when "100011001",
            "1" when "100011010",
            "1" when "100011011",
            "1" when "100011100",
            "1" when "100011101",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            neg0_0_sel <= neg0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        rec0_0_sel_next <=
            "0" when "110010111",
            "1" when "000100111",
            "1" when "001001111",
            "1" when "001110111",
            "1" when "010011111",
            "1" when "011000111",
            "1" when "011101111",
            "1" when "100010111",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            rec0_0_sel <= rec0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        out0_0_sel_next <=
            "00" when "100101010",
            "10" when "101101111",
            "10" when "101110001",
            "10" when "101110010",
            "10" when "101110011",
            "10" when "101110100",
            "10" when "101110101",
            "10" when "101110110",
            "10" when "101111100",
            "10" when "101111101",
            "10" when "101111110",
            "10" when "101111111",
            "10" when "110000000",
            "10" when "110000001",
            "10" when "110000010",
            "10" when "110000011",
            "10" when "110000100",
            "10" when "110000101",
            "10" when "110000110",
            "10" when "110000111",
            "10" when "110001000",
            "10" when "110001001",
            "10" when "110001010",
            "10" when "110001011",
            "10" when "110001100",
            "10" when "110001101",
            "10" when "110001110",
            "10" when "110001111",
            "01" when "110010000",
            "01" when "110010001",
            "01" when "110010010",
            "01" when "110010011",
            "01" when "110010100",
            "01" when "110010101",
            "01" when "110010110",
            "01" when "110010111",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            out0_0_sel <= out0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory0_0_sel_next <=
            "1" when "010100011",
            "1" when "101001100",
            "1" when "010100100",
            "1" when "101001101",
            "1" when "010100101",
            "1" when "101001110",
            "1" when "010100110",
            "1" when "101001111",
            "1" when "010100111",
            "1" when "101010000",
            "1" when "101010001",
            "1" when "101010010",
            "1" when "010101011",
            "1" when "010101100",
            "1" when "010101101",
            "1" when "010101110",
            "1" when "010101111",
            "1" when "010110000",
            "1" when "010110001",
            "1" when "010110010",
            "1" when "010110011",
            "1" when "010110100",
            "1" when "010111001",
            "1" when "010111010",
            "1" when "010111011",
            "1" when "010111100",
            "1" when "010111101",
            "1" when "010111110",
            "1" when "011001001",
            "1" when "011001011",
            "1" when "011001100",
            "1" when "011010001",
            "1" when "011010010",
            "1" when "011010011",
            "1" when "011010100",
            "1" when "011010101",
            "1" when "011010110",
            "1" when "011010111",
            "1" when "011011000",
            "1" when "011100000",
            "1" when "011100001",
            "1" when "011100011",
            "1" when "011100100",
            "1" when "011100101",
            "1" when "011100110",
            "1" when "011100111",
            "1" when "011101000",
            "1" when "011101011",
            "1" when "011101100",
            "1" when "011110001",
            "1" when "011110111",
            "1" when "011111000",
            "1" when "011111001",
            "1" when "001010001",
            "1" when "011111010",
            "1" when "011111011",
            "1" when "001010011",
            "1" when "001010100",
            "1" when "001010110",
            "1" when "001010111",
            "1" when "001011000",
            "1" when "001011010",
            "0" when "000100010",
            "1" when "000101100",
            "1" when "000101110",
            "1" when "000101111",
            "1" when "001011011",
            "1" when "100001001",
            "1" when "001011100",
            "1" when "100001010",
            "1" when "100001011",
            "1" when "000110000",
            "1" when "100001100",
            "1" when "100001110",
            "1" when "000110010",
            "1" when "000110011",
            "1" when "100010000",
            "1" when "001111001",
            "1" when "000110100",
            "1" when "001111011",
            "1" when "001111100",
            "1" when "100010010",
            "1" when "000110110",
            "1" when "100010011",
            "1" when "000110111",
            "1" when "001111110",
            "1" when "000111000",
            "1" when "100010110",
            "1" when "001111111",
            "1" when "000111001",
            "1" when "000111010",
            "1" when "010000000",
            "1" when "000111100",
            "1" when "010000010",
            "1" when "000111101",
            "1" when "010000011",
            "1" when "000111110",
            "1" when "000111111",
            "1" when "010000100",
            "1" when "001000000",
            "1" when "001000001",
            "1" when "001100001",
            "1" when "100011110",
            "1" when "100011111",
            "1" when "010000111",
            "1" when "100100000",
            "1" when "100100001",
            "1" when "010001000",
            "1" when "001100011",
            "1" when "001001000",
            "1" when "001011110",
            "1" when "010001001",
            "1" when "100100010",
            "1" when "001100100",
            "1" when "001011111",
            "1" when "010001010",
            "1" when "001100000",
            "1" when "001100101",
            "1" when "100100011",
            "1" when "010001011",
            "0" when "000000001",
            "1" when "010001100",
            "0" when "000000010",
            "1" when "001100110",
            "0" when "000000011",
            "0" when "000000100",
            "1" when "010001101",
            "1" when "001100111",
            "0" when "000000110",
            "0" when "000000111",
            "0" when "000001000",
            "1" when "001101000",
            "1" when "001101001",
            "0" when "000001011",
            "0" when "000001010",
            "0" when "000001100",
            "1" when "010001110",
            "0" when "000001110",
            "0" when "000001111",
            "0" when "000010001",
            "0" when "000010000",
            "1" when "010001111",
            "0" when "000010010",
            "1" when "010010010",
            "1" when "100111001",
            "0" when "000010110",
            "0" when "000100001",
            "1" when "100111010",
            "1" when "100111100",
            "1" when "010010110",
            "1" when "100111101",
            "1" when "100111110",
            "1" when "001110000",
            "1" when "010010111",
            "1" when "100111111",
            "0" when "000011001",
            "1" when "101000000",
            "1" when "101001010",
            "1" when "101000010",
            "0" when "000011101",
            "1" when "101000011",
            "1" when "101000101",
            "0" when "000011110",
            "1" when "101000110",
            "0" when "000011111",
            "1" when "101000111",
            "1" when "000101001",
            "1" when "000101011",
            "1" when "010100001",
            "1" when "101001001",
            "0" when "000100000",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory0_0_sel <= memory0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory1_0_sel_next <=
            "11" when "010100010",
            "10" when "010101001",
            "10" when "010101010",
            "10" when "010101011",
            "10" when "010111001",
            "11" when "011001000",
            "11" when "011001010",
            "00" when "110001000",
            "00" when "110001001",
            "00" when "110001010",
            "00" when "110001011",
            "00" when "110001100",
            "11" when "110010000",
            "00" when "110001101",
            "00" when "110001110",
            "10" when "011001110",
            "10" when "011001111",
            "10" when "011010000",
            "10" when "011010001",
            "10" when "011100001",
            "11" when "011110000",
            "10" when "001000001",
            "11" when "001010000",
            "11" when "001010010",
            "10" when "011110011",
            "11" when "001010101",
            "10" when "011110100",
            "10" when "011110101",
            "10" when "011110110",
            "11" when "001011001",
            "10" when "011110111",
            "11" when "000101101",
            "11" when "001011101",
            "11" when "000110001",
            "11" when "001111000",
            "10" when "100001001",
            "11" when "001111010",
            "11" when "000110101",
            "11" when "001111101",
            "11" when "010000001",
            "11" when "000111011",
            "10" when "100011001",
            "10" when "100011010",
            "10" when "100011011",
            "01" when "000000000",
            "10" when "100011100",
            "01" when "000000101",
            "10" when "100011101",
            "00" when "010001010",
            "10" when "010000110",
            "10" when "100011110",
            "01" when "000001001",
            "01" when "000001101",
            "10" when "010000111",
            "10" when "001100011",
            "01" when "000010011",
            "01" when "000010100",
            "01" when "000010101",
            "01" when "000010111",
            "01" when "000011000",
            "10" when "000011001",
            "01" when "000011010",
            "01" when "000011011",
            "10" when "010010001",
            "01" when "000011100",
            "10" when "001101001",
            "11" when "000101000",
            "11" when "010100000",
            "11" when "000101010",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory1_0_sel <= memory1_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory2_0_sel_next <=
            "0" when "101001010",
            "0" when "101001011",
            "0" when "101001101",
            "0" when "101001110",
            "0" when "101001111",
            "0" when "101010000",
            "0" when "101010001",
            "0" when "101010010",
            "0" when "101010011",
            "0" when "101010100",
            "0" when "101010101",
            "0" when "101010110",
            "0" when "101010111",
            "0" when "101011001",
            "0" when "101011011",
            "0" when "101011100",
            "0" when "101011101",
            "0" when "101011110",
            "0" when "101011111",
            "0" when "101100000",
            "0" when "101100001",
            "0" when "101100010",
            "0" when "101100011",
            "0" when "101100100",
            "0" when "101100111",
            "0" when "101101110",
            "0" when "101101111",
            "0" when "101110000",
            "0" when "010110110",
            "0" when "101110010",
            "0" when "010111000",
            "0" when "010111001",
            "0" when "010111011",
            "0" when "010111100",
            "0" when "010111101",
            "1" when "011011010",
            "0" when "011010000",
            "0" when "011010001",
            "0" when "011010010",
            "0" when "011010011",
            "0" when "011010100",
            "0" when "011010101",
            "0" when "011011001",
            "0" when "011100100",
            "0" when "011100101",
            "0" when "011110011",
            "0" when "011110100",
            "1" when "100000010",
            "0" when "011110101",
            "0" when "011110110",
            "0" when "011110111",
            "0" when "011111000",
            "0" when "011111001",
            "0" when "011111010",
            "1" when "001100010",
            "0" when "011111011",
            "0" when "011111100",
            "0" when "011111101",
            "0" when "011111111",
            "0" when "100000100",
            "0" when "100000110",
            "1" when "010001010",
            "0" when "000111001",
            "0" when "100011011",
            "0" when "001000000",
            "0" when "001000001",
            "0" when "100011100",
            "0" when "001000010",
            "0" when "100011101",
            "0" when "100011110",
            "0" when "001000101",
            "0" when "100011111",
            "0" when "100100001",
            "0" when "100100010",
            "0" when "100100100",
            "0" when "100100101",
            "0" when "001101000",
            "0" when "100100110",
            "0" when "010001011",
            "0" when "100100111",
            "0" when "100101000",
            "0" when "100101001",
            "0" when "100101010",
            "0" when "100101011",
            "0" when "100101100",
            "0" when "000011000",
            "0" when "100101101",
            "0" when "100101110",
            "0" when "000011001",
            "0" when "100101111",
            "0" when "000011010",
            "0" when "100110010",
            "0" when "010010000",
            "0" when "000011011",
            "0" when "010010010",
            "0" when "010010001",
            "0" when "000011100",
            "0" when "100111000",
            "0" when "000011101",
            "0" when "010010011",
            "0" when "001101101",
            "0" when "100111011",
            "0" when "010010100",
            "0" when "010010101",
            "0" when "100111111",
            "0" when "101000010",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory2_0_sel <= memory2_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory3_0_sel_next <=
            "0" when "101001100",
            "1" when "010110010",
            "0" when "101011000",
            "0" when "101011010",
            "0" when "101110001",
            "0" when "010110111",
            "0" when "010111010",
            "0" when "011100000",
            "0" when "011100001",
            "1" when "000111010",
            "0" when "100001000",
            "0" when "100001011",
            "0" when "100001100",
            "1" when "100101010",
            "0" when "001000011",
            "0" when "001000100",
            "0" when "100100000",
            "1" when "000010010",
            "0" when "001100010",
            "0" when "100100011",
            "0" when "001101001",
            "0" when "001101010",
            "0" when "001101011",
            "0" when "001101100",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory3_0_sel <= memory3_0_sel_next;
        end if;
    end process;

    -- Interconnect
    with addsub0_0_sel select
        addsub0_0_in <=
            mul0_0_out when "000",
            memory3_0_out when "001",
            memory2_0_out when "010",
            memory0_0_out when "011",
            memory1_0_out when "100",
            (others => '-') when others;

    with addsub0_1_sel select
        addsub0_1_in <=
            mul0_0_out when "0",
            memory2_0_out when "1",
            (others => '-') when others;

    with mul0_0_sel select
        mul0_0_in <=
            mul0_0_out when "000",
            memory3_0_out when "001",
            memory0_0_out when "010",
            memory2_0_out when "011",
            memory1_0_out when "100",
            (others => '-') when others;

    with mul0_1_sel select
        mul0_1_in <=
            mul0_0_out when "000",
            memory3_0_out when "001",
            rec0_0_out when "010",
            memory2_0_out when "011",
            memory1_0_out when "100",
            (others => '-') when others;

    with neg0_0_sel select
        neg0_0_in <=
            mul0_0_out when "0",
            addsub0_0_out when "1",
            (others => '-') when others;

    with rec0_0_sel select
        rec0_0_in <=
            in0_0_out when "0",
            addsub0_0_out when "1",
            (others => '-') when others;

    with out0_0_sel select
        out0_0_in <=
            rec0_0_out when "00",
            memory1_0_out when "01",
            addsub0_0_out when "10",
            (others => '-') when others;

    with memory0_0_sel select
        memory0_0_in <=
            in0_0_out when "0",
            addsub0_0_out when "1",
            (others => '-') when others;

    with memory1_0_sel select
        memory1_0_in <=
            mul0_0_out when "00",
            in0_0_out when "01",
            neg0_0_out when "10",
            addsub0_0_out when "11",
            (others => '-') when others;

    with memory2_0_sel select
        memory2_0_in <=
            mul0_0_out when "0",
            rec0_0_out when "1",
            (others => '-') when others;

    with memory3_0_sel select
        memory3_0_in <=
            mul0_0_out when "0",
            rec0_0_out when "1",
            (others => '-') when others;

end architecture rtl;


