--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2026-06-07 23:42:31.235741)
-- B-ASIC version: 0.1.0.dev970+unknown.g621314118
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ldlt is
    port (
        clk : in std_logic;
        rst : in std_logic;
        in0_0_in : in std_logic_vector(31 downto 0);
        out0_0_out : out std_logic_vector(31 downto 0)
    );
end entity ldlt;

architecture rtl of ldlt is
    -- Component declaration
    component mads0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_1_in : in std_logic_vector(31 downto 0);
            p_2_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component mads1
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_1_in : in std_logic_vector(31 downto 0);
            p_2_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component neg0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component out0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component rec0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component in0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory0
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory1
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory2
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory3
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory4
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory5
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    component memory6
        port (
            clk : in std_logic;
            en : in std_logic;
            schedule_cnt : in unsigned(8 downto 0);
            p_0_in : in std_logic_vector(31 downto 0);
            p_0_out : out std_logic_vector(31 downto 0)
        );
    end component;

    -- mads0 signals
    signal mads0_0_in : std_logic_vector(31 downto 0);
    signal mads0_1_in : std_logic_vector(31 downto 0);
    signal mads0_2_in : std_logic_vector(31 downto 0);
    signal mads0_0_out : std_logic_vector(31 downto 0);

    -- mads1 signals
    signal mads1_0_in : std_logic_vector(31 downto 0);
    signal mads1_1_in : std_logic_vector(31 downto 0);
    signal mads1_2_in : std_logic_vector(31 downto 0);
    signal mads1_0_out : std_logic_vector(31 downto 0);

    -- neg0 signals
    signal neg0_0_in : std_logic_vector(31 downto 0);
    signal neg0_0_out : std_logic_vector(31 downto 0);

    -- out0 signals
    signal out0_0_in : std_logic_vector(31 downto 0);

    -- rec0 signals
    signal rec0_0_in : std_logic_vector(31 downto 0);
    signal rec0_0_out : std_logic_vector(31 downto 0);

    -- in0 signals
    signal in0_0_out : std_logic_vector(31 downto 0);

    -- memory0 signals
    signal memory0_0_in : std_logic_vector(31 downto 0);
    signal memory0_0_out : std_logic_vector(31 downto 0);

    -- memory1 signals
    signal memory1_0_in : std_logic_vector(31 downto 0);
    signal memory1_0_out : std_logic_vector(31 downto 0);

    -- memory2 signals
    signal memory2_0_in : std_logic_vector(31 downto 0);
    signal memory2_0_out : std_logic_vector(31 downto 0);

    -- memory3 signals
    signal memory3_0_in : std_logic_vector(31 downto 0);
    signal memory3_0_out : std_logic_vector(31 downto 0);

    -- memory4 signals
    signal memory4_0_in : std_logic_vector(31 downto 0);
    signal memory4_0_out : std_logic_vector(31 downto 0);

    -- memory5 signals
    signal memory5_0_in : std_logic_vector(31 downto 0);
    signal memory5_0_out : std_logic_vector(31 downto 0);

    -- memory6 signals
    signal memory6_0_in : std_logic_vector(31 downto 0);
    signal memory6_0_out : std_logic_vector(31 downto 0);

    signal schedule_cnt : unsigned(8 downto 0) := (others => '0');

    -- Internal signals for pipelined I/O
    signal in0_0_in_internal : std_logic_vector(31 downto 0);
    signal out0_0_out_internal : std_logic_vector(31 downto 0);

    -- Multiplexer control signals
    signal mads0_0_sel : std_logic_vector(1 downto 0);
    signal mads0_0_sel_next : std_logic_vector(1 downto 0);
    signal mads0_1_sel : std_logic_vector(2 downto 0);
    signal mads0_1_sel_next : std_logic_vector(2 downto 0);
    signal mads0_2_sel : std_logic_vector(2 downto 0);
    signal mads0_2_sel_next : std_logic_vector(2 downto 0);
    signal mads1_0_sel : std_logic_vector(1 downto 0);
    signal mads1_0_sel_next : std_logic_vector(1 downto 0);
    signal mads1_1_sel : std_logic_vector(2 downto 0);
    signal mads1_1_sel_next : std_logic_vector(2 downto 0);
    signal mads1_2_sel : std_logic_vector(2 downto 0);
    signal mads1_2_sel_next : std_logic_vector(2 downto 0);
    signal neg0_0_sel : std_logic_vector(1 downto 0);
    signal neg0_0_sel_next : std_logic_vector(1 downto 0);
    signal out0_0_sel : std_logic_vector(1 downto 0);
    signal out0_0_sel_next : std_logic_vector(1 downto 0);
    signal rec0_0_sel : std_logic_vector(0 downto 0);
    signal rec0_0_sel_next : std_logic_vector(0 downto 0);
    signal memory0_0_sel : std_logic_vector(0 downto 0);
    signal memory0_0_sel_next : std_logic_vector(0 downto 0);
    signal memory1_0_sel : std_logic_vector(0 downto 0);
    signal memory1_0_sel_next : std_logic_vector(0 downto 0);
    signal memory2_0_sel : std_logic_vector(0 downto 0);
    signal memory2_0_sel_next : std_logic_vector(0 downto 0);
    signal memory3_0_sel : std_logic_vector(1 downto 0);
    signal memory3_0_sel_next : std_logic_vector(1 downto 0);
    signal memory4_0_sel : std_logic_vector(0 downto 0);
    signal memory4_0_sel_next : std_logic_vector(0 downto 0);
    signal memory5_0_sel : std_logic_vector(0 downto 0);
    signal memory5_0_sel_next : std_logic_vector(0 downto 0);
    signal memory6_0_sel : std_logic_vector(1 downto 0);
    signal memory6_0_sel_next : std_logic_vector(1 downto 0);

begin
    -- Pipelining of I/O
    input_reg_proc: process(clk)
    begin
        if rising_edge(clk) then
            in0_0_in_internal <= in0_0_in;
        end if;
    end process input_reg_proc;

    output_reg_proc: process(clk)
    begin
        if rising_edge(clk) then
            out0_0_out <= out0_0_out_internal;
        end if;
    end process output_reg_proc;

    -- Component instantiation
    mads0_inst: mads0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => mads0_0_in,
            p_1_in => mads0_1_in,
            p_2_in => mads0_2_in,
            p_0_out => mads0_0_out
        );

    mads1_inst: mads1
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => mads1_0_in,
            p_1_in => mads1_1_in,
            p_2_in => mads1_2_in,
            p_0_out => mads1_0_out
        );

    neg0_inst: neg0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => neg0_0_in,
            p_0_out => neg0_0_out
        );

    out0_inst: out0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => out0_0_in,
            p_0_out => out0_0_out_internal
        );

    rec0_inst: rec0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => rec0_0_in,
            p_0_out => rec0_0_out
        );

    in0_inst: in0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => in0_0_in_internal,
            p_0_out => in0_0_out
        );

    memory0_inst: memory0
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory0_0_in,
            p_0_out => memory0_0_out
        );

    memory1_inst: memory1
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory1_0_in,
            p_0_out => memory1_0_out
        );

    memory2_inst: memory2
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory2_0_in,
            p_0_out => memory2_0_out
        );

    memory3_inst: memory3
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory3_0_in,
            p_0_out => memory3_0_out
        );

    memory4_inst: memory4
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory4_0_in,
            p_0_out => memory4_0_out
        );

    memory5_inst: memory5
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory5_0_in,
            p_0_out => memory5_0_out
        );

    memory6_inst: memory6
        port map (
            clk => clk,
            en => '1',
            schedule_cnt => schedule_cnt,
            p_0_in => memory6_0_in,
            p_0_out => memory6_0_out
        );

    -- Schedule counter
    schedule_cnt_proc: process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                schedule_cnt <= (others => '0');
            else
                if schedule_cnt = 286 then
                    schedule_cnt <= (others => '0');
                else
                    schedule_cnt <= schedule_cnt + 1;
                end if;
            end if;
        end if;
    end process schedule_cnt_proc;

    -- Multiplexer control signal generation
    with schedule_cnt select
        mads0_0_sel_next <=
            "01" when "000010101",
            "01" when "000010110",
            "01" when "000010111",
            "00" when "000011000",
            "00" when "000011001",
            "01" when "000011010",
            "01" when "000011011",
            "01" when "000011100",
            "01" when "000011101",
            "01" when "000011110",
            "01" when "000011111",
            "01" when "000100000",
            "01" when "000100001",
            "00" when "000100010",
            "01" when "000110100",
            "01" when "000110101",
            "01" when "000110110",
            "01" when "000110111",
            "01" when "000111000",
            "01" when "000111001",
            "10" when "000111010",
            "01" when "000111011",
            "01" when "000111100",
            "01" when "000111101",
            "01" when "000111110",
            "10" when "000111111",
            "10" when "001000000",
            "10" when "001000001",
            "01" when "001010011",
            "01" when "001010100",
            "00" when "001010101",
            "01" when "001010110",
            "01" when "001010111",
            "10" when "001011000",
            "01" when "001011001",
            "01" when "001011010",
            "00" when "001011011",
            "00" when "001011100",
            "01" when "001011101",
            "00" when "001011110",
            "00" when "001011111",
            "01" when "001100000",
            "01" when "001110010",
            "01" when "001110011",
            "01" when "001110100",
            "01" when "001110101",
            "01" when "001110110",
            "01" when "001110111",
            "01" when "001111000",
            "01" when "001111001",
            "00" when "001111010",
            "01" when "001111011",
            "01" when "001111100",
            "01" when "001111101",
            "10" when "001111110",
            "01" when "001111111",
            "01" when "010010001",
            "01" when "010010010",
            "01" when "010010011",
            "01" when "010010100",
            "01" when "010010101",
            "00" when "010010110",
            "01" when "010010111",
            "01" when "010011000",
            "00" when "010011001",
            "10" when "010011010",
            "01" when "010011011",
            "00" when "010011100",
            "01" when "010011101",
            "10" when "010011110",
            "01" when "010110000",
            "01" when "010110001",
            "10" when "010110010",
            "01" when "010110011",
            "10" when "010110100",
            "01" when "010110101",
            "01" when "010110110",
            "00" when "010110111",
            "01" when "010111010",
            "01" when "010111011",
            "10" when "010111100",
            "00" when "010111101",
            "01" when "010111110",
            "01" when "010111111",
            "01" when "011001111",
            "10" when "011010000",
            "10" when "011010001",
            "01" when "011010100",
            "01" when "011010101",
            "01" when "011010110",
            "01" when "011010111",
            "01" when "011011011",
            "10" when "011011100",
            "01" when "011011101",
            "01" when "011011110",
            "10" when "011011111",
            "01" when "011100000",
            "01" when "011100001",
            "01" when "011110100",
            "00" when "011110101",
            "01" when "011110111",
            "00" when "011111001",
            "00" when "011111010",
            "00" when "011111011",
            "01" when "011111100",
            "01" when "011111101",
            "10" when "011111110",
            "10" when "011111111",
            "01" when "100000000",
            "10" when "100000001",
            "00" when "100000010",
            "01" when "100000011",
            "10" when "100000100",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mads0_0_sel <= mads0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mads0_1_sel_next <=
            "101" when "000001100",
            "101" when "000001101",
            "010" when "000010101",
            "101" when "000010110",
            "010" when "000010111",
            "101" when "000011000",
            "101" when "000011001",
            "101" when "000011010",
            "101" when "000011011",
            "101" when "000011100",
            "010" when "000011101",
            "010" when "000011110",
            "010" when "000011111",
            "101" when "000100000",
            "101" when "000100001",
            "101" when "000100010",
            "100" when "000101011",
            "100" when "000101100",
            "110" when "000101101",
            "000" when "000101110",
            "010" when "000110100",
            "100" when "000110101",
            "110" when "000110110",
            "100" when "000110111",
            "100" when "000111000",
            "110" when "000111001",
            "110" when "000111010",
            "110" when "000111011",
            "100" when "000111100",
            "100" when "000111101",
            "100" when "000111110",
            "011" when "000111111",
            "011" when "001000000",
            "110" when "001000001",
            "010" when "001001010",
            "010" when "001001011",
            "010" when "001001100",
            "101" when "001001101",
            "000" when "001001110",
            "100" when "001010011",
            "010" when "001010100",
            "100" when "001010101",
            "010" when "001010110",
            "010" when "001010111",
            "010" when "001011000",
            "010" when "001011001",
            "010" when "001011010",
            "000" when "001011011",
            "000" when "001011100",
            "110" when "001011101",
            "011" when "001011110",
            "110" when "001011111",
            "011" when "001100000",
            "110" when "001101001",
            "100" when "001101010",
            "101" when "001101011",
            "100" when "001101100",
            "100" when "001101101",
            "000" when "001101110",
            "000" when "001101111",
            "010" when "001110010",
            "110" when "001110011",
            "100" when "001110100",
            "110" when "001110101",
            "110" when "001110110",
            "010" when "001110111",
            "011" when "001111000",
            "011" when "001111001",
            "000" when "001111010",
            "010" when "001111011",
            "010" when "001111100",
            "100" when "001111101",
            "010" when "001111110",
            "010" when "001111111",
            "110" when "010001000",
            "100" when "010001001",
            "110" when "010001010",
            "101" when "010001011",
            "100" when "010001100",
            "100" when "010001101",
            "000" when "010001110",
            "000" when "010001111",
            "000" when "010010000",
            "100" when "010010001",
            "110" when "010010010",
            "100" when "010010011",
            "010" when "010010100",
            "010" when "010010101",
            "011" when "010010110",
            "011" when "010010111",
            "000" when "010011000",
            "000" when "010011001",
            "110" when "010011010",
            "100" when "010011011",
            "011" when "010011100",
            "010" when "010011101",
            "000" when "010011110",
            "110" when "010100111",
            "101" when "010101000",
            "101" when "010101001",
            "101" when "010101010",
            "110" when "010101011",
            "110" when "010101100",
            "110" when "010101101",
            "101" when "010101110",
            "011" when "010101111",
            "100" when "010110000",
            "110" when "010110001",
            "010" when "010110010",
            "010" when "010110011",
            "011" when "010110100",
            "011" when "010110101",
            "010" when "010110110",
            "011" when "010110111",
            "011" when "010111000",
            "011" when "010111001",
            "010" when "010111010",
            "100" when "010111011",
            "010" when "010111100",
            "000" when "010111101",
            "011" when "010111110",
            "000" when "010111111",
            "100" when "011000110",
            "101" when "011000111",
            "110" when "011001000",
            "110" when "011001001",
            "110" when "011001010",
            "011" when "011001011",
            "011" when "011001100",
            "101" when "011001101",
            "101" when "011001110",
            "010" when "011001111",
            "010" when "011010000",
            "010" when "011010001",
            "101" when "011010010",
            "110" when "011010011",
            "011" when "011010100",
            "000" when "011010101",
            "011" when "011010110",
            "001" when "011010111",
            "000" when "011011000",
            "000" when "011011001",
            "000" when "011011010",
            "000" when "011011011",
            "001" when "011011100",
            "011" when "011011101",
            "000" when "011011110",
            "010" when "011011111",
            "010" when "011100000",
            "000" when "011100001",
            "101" when "011100101",
            "110" when "011100110",
            "110" when "011100111",
            "110" when "011101000",
            "101" when "011101001",
            "101" when "011101010",
            "101" when "011101011",
            "101" when "011101100",
            "110" when "011101101",
            "110" when "011101110",
            "101" when "011101111",
            "101" when "011110000",
            "100" when "011110001",
            "100" when "011110010",
            "011" when "011110011",
            "010" when "011110100",
            "001" when "011110101",
            "011" when "011110110",
            "001" when "011110111",
            "011" when "011111000",
            "001" when "011111001",
            "011" when "011111010",
            "001" when "011111011",
            "110" when "011111100",
            "000" when "011111101",
            "011" when "011111110",
            "010" when "011111111",
            "100" when "100000000",
            "011" when "100000001",
            "000" when "100000010",
            "011" when "100000011",
            "010" when "100000100",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mads0_1_sel <= mads0_1_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mads0_2_sel_next <=
            "010" when "000001100",
            "000" when "000001101",
            "101" when "000010101",
            "000" when "000010110",
            "011" when "000010111",
            "000" when "000011000",
            "000" when "000011001",
            "000" when "000011010",
            "000" when "000011011",
            "011" when "000011100",
            "000" when "000011101",
            "000" when "000011110",
            "110" when "000011111",
            "011" when "000100000",
            "000" when "000100001",
            "000" when "000100010",
            "010" when "000101011",
            "000" when "000101100",
            "000" when "000101101",
            "100" when "000101110",
            "101" when "000110100",
            "001" when "000110101",
            "001" when "000110110",
            "001" when "000110111",
            "001" when "000111000",
            "001" when "000111001",
            "001" when "000111010",
            "000" when "000111011",
            "001" when "000111100",
            "001" when "000111101",
            "110" when "000111110",
            "100" when "000111111",
            "100" when "001000000",
            "100" when "001000001",
            "010" when "001001010",
            "000" when "001001011",
            "000" when "001001100",
            "000" when "001001101",
            "100" when "001001110",
            "101" when "001010011",
            "000" when "001010100",
            "000" when "001010101",
            "000" when "001010110",
            "110" when "001010111",
            "001" when "001011000",
            "000" when "001011001",
            "000" when "001011010",
            "100" when "001011011",
            "011" when "001011100",
            "011" when "001011101",
            "011" when "001011110",
            "011" when "001011111",
            "011" when "001100000",
            "010" when "001101001",
            "000" when "001101010",
            "000" when "001101011",
            "000" when "001101100",
            "000" when "001101101",
            "110" when "001101110",
            "100" when "001101111",
            "101" when "001110010",
            "001" when "001110011",
            "001" when "001110100",
            "001" when "001110101",
            "000" when "001110110",
            "110" when "001110111",
            "110" when "001111000",
            "100" when "001111001",
            "110" when "001111010",
            "110" when "001111011",
            "100" when "001111100",
            "100" when "001111101",
            "110" when "001111110",
            "100" when "001111111",
            "010" when "010001000",
            "000" when "010001001",
            "000" when "010001010",
            "000" when "010001011",
            "000" when "010001100",
            "000" when "010001101",
            "100" when "010001110",
            "110" when "010001111",
            "100" when "010010000",
            "101" when "010010001",
            "001" when "010010010",
            "001" when "010010011",
            "011" when "010010100",
            "110" when "010010101",
            "100" when "010010110",
            "110" when "010010111",
            "011" when "010011000",
            "100" when "010011001",
            "100" when "010011010",
            "110" when "010011011",
            "011" when "010011100",
            "100" when "010011101",
            "110" when "010011110",
            "010" when "010100111",
            "001" when "010101000",
            "001" when "010101001",
            "001" when "010101010",
            "001" when "010101011",
            "001" when "010101100",
            "001" when "010101101",
            "001" when "010101110",
            "100" when "010101111",
            "101" when "010110000",
            "001" when "010110001",
            "100" when "010110010",
            "110" when "010110011",
            "110" when "010110100",
            "011" when "010110101",
            "110" when "010110110",
            "110" when "010110111",
            "110" when "010111000",
            "011" when "010111001",
            "110" when "010111010",
            "100" when "010111011",
            "100" when "010111100",
            "110" when "010111101",
            "011" when "010111110",
            "011" when "010111111",
            "010" when "011000110",
            "000" when "011000111",
            "000" when "011001000",
            "000" when "011001001",
            "000" when "011001010",
            "000" when "011001011",
            "000" when "011001100",
            "000" when "011001101",
            "000" when "011001110",
            "101" when "011001111",
            "110" when "011010000",
            "001" when "011010001",
            "000" when "011010010",
            "000" when "011010011",
            "011" when "011010100",
            "011" when "011010101",
            "100" when "011010110",
            "100" when "011010111",
            "001" when "011011000",
            "100" when "011011001",
            "011" when "011011010",
            "110" when "011011011",
            "110" when "011011100",
            "110" when "011011101",
            "100" when "011011110",
            "100" when "011011111",
            "011" when "011100000",
            "001" when "011100001",
            "010" when "011100101",
            "001" when "011100110",
            "001" when "011100111",
            "001" when "011101000",
            "001" when "011101001",
            "001" when "011101010",
            "001" when "011101011",
            "001" when "011101100",
            "001" when "011101101",
            "001" when "011101110",
            "001" when "011101111",
            "001" when "011110000",
            "001" when "011110001",
            "001" when "011110010",
            "011" when "011110011",
            "011" when "011110100",
            "011" when "011110101",
            "100" when "011110110",
            "011" when "011110111",
            "011" when "011111000",
            "011" when "011111001",
            "011" when "011111010",
            "011" when "011111011",
            "011" when "011111100",
            "100" when "011111101",
            "100" when "011111110",
            "110" when "011111111",
            "110" when "100000000",
            "100" when "100000001",
            "100" when "100000010",
            "100" when "100000011",
            "100" when "100000100",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mads0_2_sel <= mads0_2_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mads1_0_sel_next <=
            "00" when "000010101",
            "00" when "000010110",
            "00" when "000010111",
            "00" when "000011000",
            "00" when "000011001",
            "00" when "000011010",
            "00" when "000011011",
            "00" when "000011100",
            "00" when "000011101",
            "00" when "000011110",
            "00" when "000100000",
            "00" when "000100001",
            "00" when "000100010",
            "00" when "000101000",
            "10" when "000110100",
            "01" when "000110101",
            "01" when "000110110",
            "01" when "000110111",
            "01" when "000111000",
            "01" when "000111001",
            "01" when "000111010",
            "00" when "000111011",
            "10" when "000111100",
            "01" when "000111101",
            "01" when "000111110",
            "01" when "000111111",
            "10" when "001000000",
            "01" when "001000001",
            "00" when "001010011",
            "00" when "001010100",
            "00" when "001010101",
            "00" when "001010110",
            "01" when "001010111",
            "01" when "001011000",
            "00" when "001011001",
            "00" when "001011010",
            "00" when "001011011",
            "00" when "001011100",
            "01" when "001011101",
            "10" when "001011110",
            "00" when "001011111",
            "01" when "001100000",
            "01" when "001110010",
            "01" when "001110011",
            "10" when "001110100",
            "01" when "001110101",
            "00" when "001110110",
            "01" when "001110111",
            "01" when "001111000",
            "10" when "001111001",
            "00" when "001111010",
            "00" when "001111011",
            "01" when "001111100",
            "00" when "001111101",
            "01" when "001111110",
            "01" when "001111111",
            "01" when "010010001",
            "01" when "010010010",
            "10" when "010010011",
            "00" when "010010100",
            "00" when "010010101",
            "10" when "010010110",
            "01" when "010010111",
            "00" when "010011000",
            "00" when "010011001",
            "00" when "010011010",
            "00" when "010011011",
            "01" when "010011100",
            "10" when "010011101",
            "00" when "010011110",
            "00" when "010110000",
            "01" when "010110001",
            "00" when "010110010",
            "00" when "010110011",
            "01" when "010110100",
            "01" when "010110101",
            "01" when "010110110",
            "01" when "010110111",
            "01" when "010111010",
            "00" when "010111011",
            "00" when "010111100",
            "00" when "010111101",
            "10" when "010111110",
            "00" when "010111111",
            "01" when "011001111",
            "01" when "011010000",
            "10" when "011010001",
            "00" when "011010010",
            "10" when "011010101",
            "00" when "011010111",
            "00" when "011011010",
            "00" when "011011011",
            "00" when "011011100",
            "01" when "011011101",
            "10" when "011011110",
            "01" when "011011111",
            "10" when "011100000",
            "10" when "011100001",
            "01" when "011110011",
            "00" when "011110100",
            "01" when "011111001",
            "01" when "011111010",
            "10" when "011111011",
            "00" when "011111100",
            "10" when "011111101",
            "01" when "011111110",
            "01" when "011111111",
            "01" when "100000000",
            "10" when "100000001",
            "00" when "100000010",
            "10" when "100000011",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mads1_0_sel <= mads1_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mads1_1_sel_next <=
            "001" when "000001100",
            "001" when "000001101",
            "011" when "000001110",
            "011" when "000010100",
            "100" when "000010101",
            "001" when "000010110",
            "001" when "000010111",
            "100" when "000011000",
            "100" when "000011001",
            "100" when "000011010",
            "100" when "000011011",
            "001" when "000011100",
            "001" when "000011101",
            "001" when "000011110",
            "100" when "000011111",
            "100" when "000100000",
            "100" when "000100001",
            "100" when "000100010",
            "100" when "000101000",
            "001" when "000101011",
            "111" when "000101100",
            "101" when "000101101",
            "100" when "000101110",
            "101" when "000110100",
            "111" when "000110101",
            "111" when "000110110",
            "101" when "000110111",
            "101" when "000111000",
            "111" when "000111001",
            "111" when "000111010",
            "101" when "000111011",
            "101" when "000111100",
            "101" when "000111101",
            "001" when "000111110",
            "001" when "000111111",
            "000" when "001000000",
            "001" when "001000001",
            "101" when "001001010",
            "101" when "001001011",
            "101" when "001001100",
            "100" when "001001101",
            "000" when "001001110",
            "001" when "001010011",
            "101" when "001010100",
            "101" when "001010101",
            "001" when "001010110",
            "001" when "001010111",
            "001" when "001011000",
            "001" when "001011001",
            "111" when "001011010",
            "111" when "001011011",
            "111" when "001011100",
            "010" when "001011101",
            "000" when "001011110",
            "000" when "001011111",
            "111" when "001100000",
            "001" when "001101001",
            "111" when "001101010",
            "111" when "001101011",
            "111" when "001101100",
            "101" when "001101101",
            "000" when "001101110",
            "111" when "001110010",
            "101" when "001110011",
            "101" when "001110100",
            "111" when "001110101",
            "111" when "001110110",
            "001" when "001110111",
            "001" when "001111000",
            "010" when "001111001",
            "000" when "001111010",
            "000" when "001111011",
            "001" when "001111100",
            "000" when "001111101",
            "010" when "001111110",
            "010" when "001111111",
            "101" when "010001000",
            "100" when "010001001",
            "100" when "010001010",
            "100" when "010001011",
            "100" when "010001100",
            "101" when "010001101",
            "111" when "010001110",
            "000" when "010001111",
            "111" when "010010001",
            "101" when "010010010",
            "101" when "010010011",
            "001" when "010010100",
            "001" when "010010101",
            "010" when "010010110",
            "010" when "010010111",
            "000" when "010011000",
            "000" when "010011001",
            "001" when "010011010",
            "000" when "010011011",
            "111" when "010011100",
            "000" when "010011101",
            "001" when "010011110",
            "101" when "010100111",
            "111" when "010101000",
            "100" when "010101001",
            "100" when "010101010",
            "100" when "010101011",
            "111" when "010101100",
            "100" when "010101101",
            "101" when "010101110",
            "101" when "010101111",
            "111" when "010110000",
            "001" when "010110001",
            "001" when "010110010",
            "001" when "010110011",
            "010" when "010110100",
            "010" when "010110101",
            "010" when "010110110",
            "110" when "010110111",
            "010" when "010111000",
            "010" when "010111001",
            "010" when "010111010",
            "111" when "010111011",
            "000" when "010111100",
            "101" when "010111101",
            "000" when "010111110",
            "001" when "010111111",
            "001" when "011000110",
            "100" when "011000111",
            "111" when "011001000",
            "111" when "011001001",
            "111" when "011001010",
            "010" when "011001011",
            "010" when "011001100",
            "010" when "011001101",
            "100" when "011001110",
            "110" when "011001111",
            "001" when "011010000",
            "001" when "011010001",
            "001" when "011010010",
            "111" when "011010011",
            "111" when "011010100",
            "001" when "011010101",
            "000" when "011010110",
            "001" when "011010111",
            "000" when "011011000",
            "000" when "011011001",
            "001" when "011011010",
            "101" when "011011011",
            "110" when "011011100",
            "110" when "011011101",
            "010" when "011011110",
            "111" when "011011111",
            "000" when "011100000",
            "001" when "011100001",
            "101" when "011100101",
            "111" when "011100110",
            "111" when "011100111",
            "111" when "011101000",
            "111" when "011101001",
            "100" when "011101010",
            "100" when "011101011",
            "111" when "011101100",
            "111" when "011101101",
            "111" when "011101110",
            "100" when "011101111",
            "100" when "011110000",
            "101" when "011110001",
            "100" when "011110010",
            "001" when "011110011",
            "000" when "011110100",
            "010" when "011110101",
            "010" when "011110110",
            "010" when "011110111",
            "010" when "011111000",
            "010" when "011111001",
            "110" when "011111010",
            "110" when "011111011",
            "001" when "011111100",
            "001" when "011111101",
            "001" when "011111110",
            "010" when "011111111",
            "010" when "100000000",
            "001" when "100000001",
            "111" when "100000010",
            "101" when "100000011",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mads1_1_sel <= mads1_1_sel_next;
        end if;
    end process;

    with schedule_cnt select
        mads1_2_sel_next <=
            "011" when "000001100",
            "000" when "000001101",
            "000" when "000001110",
            "000" when "000010100",
            "110" when "000010101",
            "111" when "000010110",
            "000" when "000010111",
            "111" when "000011000",
            "100" when "000011001",
            "111" when "000011010",
            "100" when "000011011",
            "111" when "000011100",
            "100" when "000011101",
            "100" when "000011110",
            "000" when "000011111",
            "111" when "000100000",
            "100" when "000100001",
            "111" when "000100010",
            "110" when "000101000",
            "011" when "000101011",
            "000" when "000101100",
            "000" when "000101101",
            "000" when "000101110",
            "110" when "000110100",
            "001" when "000110101",
            "001" when "000110110",
            "001" when "000110111",
            "001" when "000111000",
            "001" when "000111001",
            "001" when "000111010",
            "001" when "000111011",
            "000" when "000111100",
            "001" when "000111101",
            "101" when "000111110",
            "101" when "000111111",
            "101" when "001000000",
            "101" when "001000001",
            "011" when "001001010",
            "000" when "001001011",
            "000" when "001001100",
            "000" when "001001101",
            "100" when "001001110",
            "110" when "001010011",
            "111" when "001010100",
            "111" when "001010101",
            "111" when "001010110",
            "010" when "001010111",
            "111" when "001011000",
            "111" when "001011001",
            "101" when "001011010",
            "100" when "001011011",
            "101" when "001011100",
            "101" when "001011101",
            "101" when "001011110",
            "100" when "001011111",
            "101" when "001100000",
            "011" when "001101001",
            "000" when "001101010",
            "000" when "001101011",
            "000" when "001101100",
            "000" when "001101101",
            "100" when "001101110",
            "110" when "001110010",
            "001" when "001110011",
            "000" when "001110100",
            "001" when "001110101",
            "001" when "001110110",
            "101" when "001110111",
            "100" when "001111000",
            "100" when "001111001",
            "101" when "001111010",
            "100" when "001111011",
            "100" when "001111100",
            "101" when "001111101",
            "111" when "001111110",
            "100" when "001111111",
            "011" when "010001000",
            "000" when "010001001",
            "000" when "010001010",
            "000" when "010001011",
            "000" when "010001100",
            "000" when "010001101",
            "000" when "010001110",
            "100" when "010001111",
            "110" when "010010001",
            "001" when "010010010",
            "000" when "010010011",
            "101" when "010010100",
            "101" when "010010101",
            "100" when "010010110",
            "101" when "010010111",
            "101" when "010011000",
            "111" when "010011001",
            "101" when "010011010",
            "101" when "010011011",
            "101" when "010011100",
            "100" when "010011101",
            "111" when "010011110",
            "011" when "010100111",
            "010" when "010101000",
            "010" when "010101001",
            "010" when "010101010",
            "010" when "010101011",
            "010" when "010101100",
            "010" when "010101101",
            "010" when "010101110",
            "010" when "010101111",
            "110" when "010110000",
            "100" when "010110001",
            "111" when "010110010",
            "101" when "010110011",
            "101" when "010110100",
            "111" when "010110101",
            "101" when "010110110",
            "100" when "010110111",
            "101" when "010111000",
            "111" when "010111001",
            "101" when "010111010",
            "101" when "010111011",
            "111" when "010111100",
            "111" when "010111101",
            "100" when "010111110",
            "111" when "010111111",
            "011" when "011000110",
            "000" when "011000111",
            "000" when "011001000",
            "000" when "011001001",
            "000" when "011001010",
            "000" when "011001011",
            "000" when "011001100",
            "000" when "011001101",
            "000" when "011001110",
            "100" when "011001111",
            "101" when "011010000",
            "101" when "011010001",
            "111" when "011010010",
            "000" when "011010011",
            "000" when "011010100",
            "101" when "011010101",
            "101" when "011010110",
            "101" when "011010111",
            "111" when "011011000",
            "111" when "011011001",
            "111" when "011011010",
            "111" when "011011011",
            "101" when "011011100",
            "100" when "011011101",
            "100" when "011011110",
            "101" when "011011111",
            "010" when "011100000",
            "100" when "011100001",
            "011" when "011100101",
            "010" when "011100110",
            "010" when "011100111",
            "010" when "011101000",
            "010" when "011101001",
            "010" when "011101010",
            "010" when "011101011",
            "010" when "011101100",
            "010" when "011101101",
            "010" when "011101110",
            "010" when "011101111",
            "010" when "011110000",
            "010" when "011110001",
            "010" when "011110010",
            "100" when "011110011",
            "100" when "011110100",
            "111" when "011110101",
            "111" when "011110110",
            "101" when "011110111",
            "101" when "011111000",
            "111" when "011111001",
            "100" when "011111010",
            "101" when "011111011",
            "100" when "011111100",
            "100" when "011111101",
            "101" when "011111110",
            "101" when "011111111",
            "111" when "100000000",
            "101" when "100000001",
            "101" when "100000010",
            "101" when "100000011",
            "---" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            mads1_2_sel <= mads1_2_sel_next;
        end if;
    end process;

    with schedule_cnt select
        neg0_0_sel_next <=
            "10" when "000010101",
            "10" when "000110100",
            "10" when "001000111",
            "10" when "001010011",
            "10" when "001100011",
            "10" when "001100100",
            "10" when "001110010",
            "10" when "010000000",
            "01" when "010000001",
            "00" when "010000010",
            "10" when "010010001",
            "10" when "010011101",
            "01" when "010011110",
            "01" when "010011111",
            "00" when "010100000",
            "10" when "010110000",
            "10" when "010111010",
            "10" when "010111011",
            "01" when "010111100",
            "01" when "010111101",
            "00" when "010111110",
            "10" when "011001111",
            "10" when "011011000",
            "10" when "011011001",
            "01" when "011011010",
            "00" when "011011011",
            "01" when "011011100",
            "00" when "011011101",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            neg0_0_sel <= neg0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        out0_0_sel_next <=
            "10" when "011100101",
            "11" when "011111100",
            "11" when "011111101",
            "11" when "011111110",
            "11" when "011111111",
            "11" when "100000000",
            "11" when "100000001",
            "11" when "100000010",
            "11" when "100000011",
            "11" when "100000100",
            "11" when "100000101",
            "11" when "100000110",
            "00" when "100000111",
            "01" when "100001000",
            "00" when "100001001",
            "01" when "100001010",
            "00" when "100001011",
            "01" when "100001100",
            "00" when "100001101",
            "00" when "100001110",
            "01" when "100001111",
            "00" when "100010000",
            "01" when "100010001",
            "00" when "100010010",
            "01" when "100010011",
            "01" when "100010100",
            "00" when "100010101",
            "00" when "100010110",
            "00" when "100010111",
            "00" when "100011000",
            "01" when "100011001",
            "01" when "100011010",
            "01" when "100011011",
            "00" when "100011100",
            "00" when "100011101",
            "00" when "100011110",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            out0_0_sel <= out0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        rec0_0_sel_next <=
            "0" when "100011110",
            "1" when "000011110",
            "1" when "000111101",
            "1" when "001011100",
            "1" when "001111011",
            "1" when "010011010",
            "1" when "010111001",
            "1" when "011011000",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            rec0_0_sel <= rec0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory0_0_sel_next <=
            "0" when "001111110",
            "0" when "010000110",
            "0" when "010000111",
            "1" when "010000011",
            "0" when "010010111",
            "0" when "010011000",
            "0" when "010011010",
            "0" when "001111011",
            "0" when "010011111",
            "0" when "010100001",
            "1" when "010100000",
            "0" when "010110010",
            "0" when "010110101",
            "0" when "010111101",
            "0" when "010111111",
            "1" when "010111100",
            "0" when "011000100",
            "0" when "011000110",
            "0" when "000100111",
            "0" when "000101000",
            "0" when "011010111",
            "0" when "000101011",
            "0" when "011011111",
            "0" when "000111101",
            "1" when "011011001",
            "0" when "001000000",
            "1" when "011011011",
            "0" when "011100011",
            "0" when "001000101",
            "1" when "001001000",
            "0" when "011101000",
            "0" when "011101001",
            "1" when "001010100",
            "0" when "011110011",
            "0" when "001011111",
            "0" when "011110111",
            "0" when "000010110",
            "0" when "001101001",
            "0" when "000010111",
            "0" when "000011111",
            "0" when "001110101",
            "0" when "000100011",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory0_0_sel <= memory0_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory1_0_sel_next <=
            "0" when "001111111",
            "0" when "010000100",
            "1" when "010000010",
            "0" when "010010010",
            "0" when "010010011",
            "0" when "010011011",
            "1" when "010011110",
            "0" when "010100111",
            "1" when "010100001",
            "0" when "010110110",
            "1" when "010110001",
            "0" when "001111100",
            "0" when "010111110",
            "0" when "011000000",
            "0" when "011000010",
            "0" when "011000011",
            "1" when "010111101",
            "0" when "011000101",
            "0" when "000100101",
            "0" when "011010010",
            "0" when "000101001",
            "1" when "011010000",
            "0" when "000110110",
            "0" when "011011110",
            "0" when "011100000",
            "0" when "011100001",
            "0" when "011100100",
            "1" when "011011101",
            "0" when "001010011",
            "0" when "001010100",
            "0" when "001010101",
            "0" when "001010110",
            "0" when "011110100",
            "0" when "001011101",
            "0" when "001100000",
            "0" when "001100001",
            "0" when "011111001",
            "0" when "000010101",
            "0" when "000011101",
            "1" when "001100100",
            "0" when "000100000",
            "0" when "000100001",
            "0" when "001110111",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory1_0_sel <= memory1_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory2_0_sel_next <=
            "1" when "010000001",
            "1" when "010010010",
            "1" when "001110011",
            "1" when "010011111",
            "1" when "010111011",
            "1" when "010111110",
            "0" when "000011011",
            "1" when "000110101",
            "1" when "011011010",
            "1" when "011011100",
            "1" when "011011110",
            "0" when "000000010",
            "1" when "001100101",
            "0" when "000001001",
            "0" when "000001110",
            "1" when "000010110",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory2_0_sel <= memory2_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory3_0_sel_next <=
            "11" when "010000010",
            "11" when "010000100",
            "11" when "010000101",
            "11" when "010000110",
            "11" when "010001000",
            "11" when "010010001",
            "11" when "010010101",
            "11" when "010010111",
            "11" when "010011001",
            "11" when "010011100",
            "11" when "010011111",
            "10" when "010100111",
            "11" when "010100101",
            "11" when "010100110",
            "11" when "010110000",
            "11" when "010110001",
            "11" when "010110010",
            "11" when "010110111",
            "11" when "011000100",
            "01" when "010111111",
            "11" when "011000111",
            "11" when "011001000",
            "11" when "011001111",
            "00" when "000011100",
            "11" when "011010010",
            "11" when "011010011",
            "00" when "000011111",
            "00" when "000100001",
            "11" when "000101011",
            "00" when "000100010",
            "11" when "000110100",
            "11" when "011011011",
            "11" when "000110101",
            "11" when "011011110",
            "11" when "011100000",
            "10" when "011100101",
            "11" when "000111111",
            "11" when "001000000",
            "11" when "001000001",
            "11" when "001000011",
            "11" when "001000101",
            "11" when "011100100",
            "11" when "001001000",
            "11" when "001001010",
            "11" when "001010100",
            "11" when "011101111",
            "11" when "011110000",
            "11" when "001010110",
            "11" when "011110001",
            "11" when "011110010",
            "11" when "011110011",
            "11" when "011110100",
            "11" when "011110110",
            "11" when "001100011",
            "11" when "011111100",
            "11" when "011111101",
            "11" when "011111110",
            "11" when "011111111",
            "00" when "000000011",
            "11" when "100000001",
            "00" when "000000110",
            "00" when "000000111",
            "11" when "100000101",
            "11" when "001100111",
            "00" when "000001010",
            "11" when "100000110",
            "11" when "100000111",
            "00" when "000001100",
            "11" when "001101000",
            "11" when "100001000",
            "11" when "100001001",
            "11" when "100001010",
            "11" when "100001011",
            "11" when "100001100",
            "11" when "100001101",
            "00" when "000010000",
            "00" when "000010010",
            "00" when "000010101",
            "11" when "001110010",
            "00" when "000010111",
            "11" when "001110101",
            "11" when "001110111",
            "11" when "001110110",
            "00" when "000011001",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory3_0_sel <= memory3_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory4_0_sel_next <=
            "0" when "010000001",
            "0" when "010000011",
            "0" when "010001000",
            "0" when "010010001",
            "0" when "010010100",
            "0" when "010010101",
            "0" when "010010110",
            "0" when "010011110",
            "0" when "010100011",
            "0" when "010100101",
            "0" when "010110000",
            "0" when "010110001",
            "0" when "010110011",
            "0" when "010110100",
            "0" when "010111000",
            "0" when "010111001",
            "0" when "010111100",
            "0" when "011001111",
            "0" when "011010000",
            "0" when "011010001",
            "0" when "011010011",
            "0" when "011010100",
            "0" when "011010101",
            "0" when "011010110",
            "1" when "000100000",
            "0" when "000110100",
            "0" when "011011010",
            "0" when "000110101",
            "0" when "011011011",
            "0" when "000110111",
            "0" when "000111110",
            "0" when "001000001",
            "0" when "001000010",
            "0" when "011100010",
            "0" when "001000100",
            "0" when "011100101",
            "0" when "001001000",
            "0" when "001001001",
            "0" when "011100110",
            "0" when "001001010",
            "0" when "011100111",
            "0" when "011101010",
            "0" when "011101110",
            "0" when "011101111",
            "0" when "011110000",
            "0" when "011110001",
            "0" when "011110010",
            "0" when "001011100",
            "0" when "011110101",
            "0" when "011110110",
            "0" when "011111000",
            "1" when "000000000",
            "1" when "000000101",
            "0" when "001100110",
            "1" when "000001011",
            "1" when "000001101",
            "1" when "000010100",
            "0" when "000011110",
            "0" when "001110010",
            "0" when "001110011",
            "0" when "001110100",
            "0" when "001110110",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory4_0_sel <= memory4_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory5_0_sel_next <=
            "1" when "001111101",
            "1" when "001111110",
            "0" when "010001000",
            "1" when "010010010",
            "1" when "010010011",
            "1" when "010010100",
            "1" when "010010110",
            "1" when "010100000",
            "1" when "010100001",
            "1" when "010100010",
            "1" when "000100011",
            "1" when "010100100",
            "1" when "010110011",
            "1" when "010110100",
            "1" when "010110101",
            "1" when "010110110",
            "1" when "010111101",
            "1" when "010111110",
            "1" when "011000000",
            "1" when "011000001",
            "0" when "011000110",
            "1" when "011010000",
            "1" when "000100110",
            "1" when "011010001",
            "0" when "000101011",
            "1" when "000100111",
            "1" when "011010100",
            "1" when "011010101",
            "1" when "011010110",
            "1" when "000101010",
            "1" when "000110110",
            "1" when "011011101",
            "1" when "011100001",
            "1" when "011100010",
            "1" when "001000100",
            "0" when "001001010",
            "1" when "001000110",
            "1" when "011100101",
            "1" when "011101000",
            "1" when "001010011",
            "1" when "011101110",
            "1" when "001010101",
            "1" when "001010111",
            "1" when "001011110",
            "1" when "001011111",
            "1" when "011111000",
            "1" when "001100010",
            "1" when "011111010",
            "0" when "001101001",
            "1" when "001100101",
            "0" when "000001100",
            "1" when "000100100",
            "1" when "000010101",
            "1" when "000010110",
            "1" when "001110011",
            "1" when "001110100",
            "1" when "000100001",
            "1" when "000100010",
            "-" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory5_0_sel <= memory5_0_sel_next;
        end if;
    end process;

    with schedule_cnt select
        memory6_0_sel_next <=
            "01" when "001111101",
            "10" when "001111111",
            "10" when "010000000",
            "10" when "010000001",
            "01" when "010000010",
            "10" when "010000011",
            "01" when "010000101",
            "10" when "010000111",
            "10" when "010011000",
            "10" when "010011011",
            "01" when "010011100",
            "10" when "010011101",
            "10" when "010011110",
            "01" when "010100000",
            "01" when "010100010",
            "10" when "010100011",
            "01" when "010100100",
            "01" when "010100110",
            "10" when "010100111",
            "10" when "001100110",
            "10" when "010111000",
            "10" when "010111010",
            "10" when "001111100",
            "10" when "010111011",
            "10" when "010111100",
            "10" when "010111111",
            "01" when "011000001",
            "10" when "011000010",
            "10" when "011000011",
            "10" when "011000101",
            "10" when "011000110",
            "01" when "011000111",
            "10" when "000100101",
            "01" when "011001000",
            "01" when "000100110",
            "00" when "000011101",
            "00" when "000011110",
            "10" when "000101000",
            "10" when "000101001",
            "01" when "000101010",
            "01" when "000110001",
            "10" when "011011001",
            "10" when "011011010",
            "10" when "000110111",
            "10" when "011011111",
            "10" when "000111110",
            "01" when "000111111",
            "10" when "001000010",
            "01" when "001000011",
            "10" when "011100011",
            "01" when "001000110",
            "10" when "001000111",
            "10" when "001001001",
            "10" when "011100110",
            "10" when "011100111",
            "10" when "011101001",
            "10" when "011101010",
            "01" when "001010111",
            "10" when "001011101",
            "01" when "001011110",
            "10" when "001100000",
            "10" when "001100001",
            "01" when "001100010",
            "10" when "001100100",
            "01" when "001100101",
            "00" when "000000001",
            "10" when "100000000",
            "00" when "000000100",
            "10" when "100000010",
            "00" when "000011010",
            "01" when "000100100",
            "10" when "100000011",
            "10" when "100000100",
            "00" when "000001000",
            "01" when "001100111",
            "01" when "001101000",
            "01" when "100000111",
            "01" when "100001000",
            "01" when "100001001",
            "10" when "001101001",
            "01" when "100001010",
            "01" when "100001011",
            "01" when "100001100",
            "00" when "000001111",
            "00" when "000010001",
            "00" when "000010011",
            "10" when "000011111",
            "00" when "000010110",
            "10" when "000100000",
            "00" when "000011000",
            "01" when "000100010",
            "10" when "001111000",
            "--" when others;
    process(clk)
    begin
        if rising_edge(clk) then
            memory6_0_sel <= memory6_0_sel_next;
        end if;
    end process;

    -- Interconnect
    with mads0_0_sel select
        mads0_0_in <=
            memory4_0_out when "00",
            memory6_0_out when "01",
            memory0_0_out when "10",
            (others => '-') when others;

    with mads0_1_sel select
        mads0_1_in <=
            memory5_0_out when "000",
            mads0_0_out when "001",
            memory4_0_out when "010",
            memory3_0_out when "011",
            memory0_0_out when "100",
            memory2_0_out when "101",
            memory1_0_out when "110",
            (others => '-') when others;

    with mads0_2_sel select
        mads0_2_in <=
            memory5_0_out when "000",
            memory3_0_out when "001",
            rec0_0_out when "010",
            memory0_0_out when "011",
            memory2_0_out when "100",
            mads1_0_out when "101",
            memory1_0_out when "110",
            (others => '-') when others;

    with mads1_0_sel select
        mads1_0_in <=
            memory3_0_out when "00",
            memory5_0_out when "01",
            memory1_0_out when "10",
            (others => '-') when others;

    with mads1_1_sel select
        mads1_1_in <=
            memory5_0_out when "000",
            memory4_0_out when "001",
            memory3_0_out when "010",
            in0_0_out when "011",
            memory2_0_out when "100",
            memory0_0_out when "101",
            mads1_0_out when "110",
            memory1_0_out when "111",
            (others => '-') when others;

    with mads1_2_sel select
        mads1_2_in <=
            memory5_0_out when "000",
            memory4_0_out when "001",
            memory3_0_out when "010",
            rec0_0_out when "011",
            memory0_0_out when "100",
            memory2_0_out when "101",
            mads1_0_out when "110",
            memory1_0_out when "111",
            (others => '-') when others;

    with neg0_0_sel select
        neg0_0_in <=
            memory4_0_out when "00",
            memory6_0_out when "01",
            mads1_0_out when "10",
            (others => '-') when others;

    with out0_0_sel select
        out0_0_in <=
            memory3_0_out when "00",
            memory6_0_out when "01",
            rec0_0_out when "10",
            mads1_0_out when "11",
            (others => '-') when others;

    with rec0_0_sel select
        rec0_0_in <=
            in0_0_out when "0",
            mads0_0_out when "1",
            (others => '-') when others;

    with memory0_0_sel select
        memory0_0_in <=
            mads1_0_out when "0",
            neg0_0_out when "1",
            (others => '-') when others;

    with memory1_0_sel select
        memory1_0_in <=
            mads1_0_out when "0",
            neg0_0_out when "1",
            (others => '-') when others;

    with memory2_0_sel select
        memory2_0_in <=
            in0_0_out when "0",
            neg0_0_out when "1",
            (others => '-') when others;

    with memory3_0_sel select
        memory3_0_in <=
            in0_0_out when "00",
            neg0_0_out when "01",
            rec0_0_out when "10",
            mads0_0_out when "11",
            (others => '-') when others;

    with memory4_0_sel select
        memory4_0_in <=
            mads1_0_out when "0",
            in0_0_out when "1",
            (others => '-') when others;

    with memory5_0_sel select
        memory5_0_in <=
            rec0_0_out when "0",
            mads0_0_out when "1",
            (others => '-') when others;

    with memory6_0_sel select
        memory6_0_in <=
            in0_0_out when "00",
            mads1_0_out when "01",
            mads0_0_out when "10",
            (others => '-') when others;

end architecture rtl;


