--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2026-03-29 19:32:06.905204)
-- B-ASIC version: 0.1.0.dev899+unknown.gf73aa1c31
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mads0 is
    port (
        clk : in std_logic;
        en : in std_logic;
        schedule_cnt : in unsigned(8 downto 0);
        p_0_in : in std_logic_vector(31 downto 0);
        p_1_in : in std_logic_vector(31 downto 0);
        p_2_in : in std_logic_vector(31 downto 0);
        p_0_out : out std_logic_vector(31 downto 0)
    );
end entity mads0;

architecture rtl of mads0 is
    signal res_overflow_0_reg_0 : std_logic_vector(31 downto 0) := (others => '0');
    signal p_0_in_reg_0 : std_logic_vector(31 downto 0) := (others => '0');
    signal p_1_in_reg_0 : std_logic_vector(31 downto 0) := (others => '0');
    signal p_2_in_reg_0 : std_logic_vector(31 downto 0) := (others => '0');
    signal op_0 : std_logic_vector(31 downto 0);
    signal op_1 : std_logic_vector(31 downto 0);
    signal op_2 : std_logic_vector(31 downto 0);
    signal is_add : std_logic;
    signal is_add_comb : std_logic;
    signal do_addsub : std_logic;
    signal do_addsub_comb : std_logic;
    constant WL_IS_ADD_INT : integer := 1;
    constant WL_DO_ADDSUB_INT : integer := 1;
    component fp_mul
        port (
            aclk : in std_logic;
            s_axis_a_tdata : in std_logic_vector(31 downto 0);
            s_axis_a_tvalid : in std_logic;
            s_axis_b_tdata : in std_logic_vector(31 downto 0);
            s_axis_b_tvalid : in std_logic;
            m_axis_result_tdata : out std_logic_vector(31 downto 0);
            m_axis_result_tvalid : out std_logic
        );
    end component fp_mul;
    component fp_addsub
        port (
            aclk : in std_logic;
            s_axis_a_tdata : in std_logic_vector(31 downto 0);
            s_axis_a_tvalid : in std_logic;
            s_axis_b_tdata : in std_logic_vector(31 downto 0);
            s_axis_b_tvalid : in std_logic;
            s_axis_operation_tdata : in std_logic_vector(7 downto 0);
            s_axis_operation_tvalid : in std_logic;
            m_axis_result_tdata : out std_logic_vector(31 downto 0);
            m_axis_result_tvalid : out std_logic
        );
    end component fp_addsub;
    signal mul_result : std_logic_vector(31 downto 0);
    signal mul_result_tvalid_unused : std_logic;
    signal res_arith_0 : std_logic_vector(31 downto 0);
    signal fp_result_tvalid : std_logic;
    signal addsub_a : std_logic_vector(31 downto 0);
    signal addsub_op : std_logic_vector(7 downto 0);
    signal mul_result_in : std_logic_vector(31 downto 0);
    signal mul_result_reg : std_logic_vector(31 downto 0);
    signal res_quant_0 : std_logic_vector(31 downto 0);
    signal res_overflow_0 : std_logic_vector(31 downto 0);

begin
    process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                res_overflow_0_reg_0 <= res_overflow_0;
                p_0_in_reg_0 <= p_0_in;
                p_1_in_reg_0 <= p_1_in;
                p_2_in_reg_0 <= p_2_in;
                is_add <= is_add_comb;
                do_addsub <= do_addsub_comb;
            end if;
        end if;
    end process;
    op_0 <= p_0_in_reg_0;
    op_1 <= p_1_in_reg_0;
    op_2 <= p_2_in_reg_0;
    with schedule_cnt select
        is_add_comb <=
            '1' when "000001111",
            '1' when "000010000",
            '1' when "000010001",
            '0' when "000010111",
            '1' when "000010110",
            '0' when "000011000",
            '0' when "000011001",
            '0' when "000011010",
            '0' when "000011011",
            '0' when "000011100",
            '1' when "011110011",
            '0' when "000011110",
            '0' when "000011101",
            '1' when "011110101",
            '1' when "011110100",
            '0' when "000100000",
            '1' when "011110110",
            '0' when "000011111",
            '0' when "000100001",
            '1' when "011110111",
            '1' when "011111000",
            '0' when "000100010",
            '0' when "000100011",
            '1' when "000100100",
            '1' when "000101100",
            '1' when "000101110",
            '1' when "000101101",
            '1' when "000101111",
            '1' when "000110000",
            '0' when "000110100",
            '0' when "000110101",
            '0' when "000110111",
            '0' when "000110110",
            '0' when "000111001",
            '0' when "000111000",
            '0' when "000111010",
            '0' when "000111011",
            '0' when "000111100",
            '1' when "000111110",
            '0' when "000111101",
            '1' when "000111111",
            '1' when "001000001",
            '1' when "001000000",
            '0' when "010001011",
            '1' when "010001010",
            '1' when "001001010",
            '1' when "001001001",
            '0' when "010001100",
            '1' when "001001011",
            '1' when "001001101",
            '1' when "001001100",
            '0' when "001010001",
            '0' when "001010010",
            '0' when "001010100",
            '0' when "010001101",
            '0' when "001010011",
            '0' when "001010101",
            '0' when "001010111",
            '0' when "001010110",
            '1' when "001011000",
            '1' when "001011001",
            '1' when "001011010",
            '1' when "001011011",
            '1' when "001011100",
            '1' when "001011110",
            '1' when "001011101",
            '1' when "001100110",
            '1' when "001100111",
            '1' when "001101000",
            '1' when "001101010",
            '1' when "001101001",
            '1' when "001101100",
            '1' when "001101011",
            '0' when "001101110",
            '1' when "010001111",
            '1' when "010001110",
            '1' when "010010000",
            '0' when "001110000",
            '0' when "001101111",
            '0' when "001110001",
            '1' when "001110010",
            '1' when "001110100",
            '1' when "001110011",
            '1' when "001110101",
            '1' when "001110110",
            '1' when "001111000",
            '1' when "001110111",
            '1' when "001111001",
            '1' when "001111010",
            '1' when "001111011",
            '1' when "010000011",
            '1' when "010000101",
            '1' when "010000100",
            '1' when "010000111",
            '1' when "010000110",
            '1' when "010001000",
            '1' when "010001001",
            '1' when "011010110",
            '1' when "011010001",
            '1' when "011010101",
            '1' when "011010011",
            '1' when "011010100",
            '1' when "011010010",
            '1' when "011010000",
            '1' when "011001111",
            '1' when "011001110",
            '1' when "011001010",
            '1' when "011110000",
            '1' when "011110001",
            '1' when "011001100",
            '1' when "011001101",
            '1' when "011001001",
            '1' when "011001011",
            '1' when "011000011",
            '1' when "011001000",
            '1' when "011000111",
            '1' when "011000101",
            '1' when "011000110",
            '1' when "011000001",
            '1' when "011000100",
            '1' when "011000010",
            '1' when "011000000",
            '1' when "010111110",
            '1' when "010111101",
            '1' when "010111111",
            '1' when "011101111",
            '1' when "010111000",
            '1' when "010110111",
            '1' when "010110110",
            '1' when "011011000",
            '1' when "011101110",
            '1' when "010110101",
            '1' when "011011010",
            '1' when "010110100",
            '1' when "010110011",
            '1' when "010110010",
            '1' when "011010111",
            '1' when "010110001",
            '1' when "010110000",
            '1' when "010101111",
            '1' when "010101101",
            '1' when "010101100",
            '1' when "010101110",
            '1' when "010101011",
            '1' when "011011011",
            '1' when "010101001",
            '1' when "010101010",
            '1' when "010100110",
            '0' when "010101000",
            '1' when "010100101",
            '1' when "010100100",
            '1' when "010100011",
            '1' when "010100111",
            '1' when "011101011",
            '1' when "010010010",
            '1' when "010100001",
            '1' when "011101101",
            '1' when "010010101",
            '1' when "010100010",
            '1' when "010100000",
            '1' when "010011000",
            '1' when "010010100",
            '1' when "010010111",
            '1' when "010010110",
            '1' when "011101100",
            '1' when "010010011",
            '1' when "011011110",
            '1' when "011011100",
            '1' when "011011101",
            '1' when "011100000",
            '1' when "011011111",
            '1' when "011100001",
            '1' when "011100010",
            '1' when "011100100",
            '1' when "011100011",
            '1' when "011100101",
            '1' when "011100110",
            '1' when "011101000",
            '1' when "011100111",
            '1' when "011101001",
            '1' when "011101010",
            '1' when "011110010",
            '1' when "010010001",
            '-' when others;

    with schedule_cnt select
        do_addsub_comb <=
            '0' when "000001111",
            '0' when "000010000",
            '0' when "000010001",
            '1' when "000010111",
            '0' when "000010110",
            '1' when "000011000",
            '1' when "000011001",
            '1' when "000011010",
            '1' when "000011011",
            '1' when "000011100",
            '1' when "011110011",
            '1' when "000011110",
            '1' when "000011101",
            '1' when "011110101",
            '1' when "011110100",
            '1' when "000100000",
            '1' when "011110110",
            '1' when "000011111",
            '1' when "000100001",
            '1' when "011110111",
            '1' when "011111000",
            '1' when "000100010",
            '1' when "000100011",
            '0' when "000100100",
            '0' when "000101100",
            '0' when "000101110",
            '0' when "000101101",
            '0' when "000101111",
            '0' when "000110000",
            '1' when "000110100",
            '1' when "000110101",
            '1' when "000110111",
            '1' when "000110110",
            '1' when "000111001",
            '1' when "000111000",
            '1' when "000111010",
            '1' when "000111011",
            '1' when "000111100",
            '1' when "000111110",
            '1' when "000111101",
            '1' when "000111111",
            '1' when "001000001",
            '1' when "001000000",
            '1' when "010001011",
            '0' when "010001010",
            '0' when "001001010",
            '0' when "001001001",
            '1' when "010001100",
            '0' when "001001011",
            '0' when "001001101",
            '0' when "001001100",
            '1' when "001010001",
            '1' when "001010010",
            '1' when "001010100",
            '1' when "010001101",
            '1' when "001010011",
            '1' when "001010101",
            '1' when "001010111",
            '1' when "001010110",
            '1' when "001011000",
            '1' when "001011001",
            '1' when "001011010",
            '1' when "001011011",
            '1' when "001011100",
            '1' when "001011110",
            '1' when "001011101",
            '0' when "001100110",
            '0' when "001100111",
            '0' when "001101000",
            '0' when "001101010",
            '0' when "001101001",
            '0' when "001101100",
            '0' when "001101011",
            '1' when "001101110",
            '1' when "010001111",
            '1' when "010001110",
            '1' when "010010000",
            '1' when "001110000",
            '1' when "001101111",
            '1' when "001110001",
            '1' when "001110010",
            '1' when "001110100",
            '1' when "001110011",
            '1' when "001110101",
            '1' when "001110110",
            '1' when "001111000",
            '1' when "001110111",
            '1' when "001111001",
            '1' when "001111010",
            '1' when "001111011",
            '0' when "010000011",
            '0' when "010000101",
            '0' when "010000100",
            '0' when "010000111",
            '0' when "010000110",
            '0' when "010001000",
            '0' when "010001001",
            '1' when "011010110",
            '1' when "011010001",
            '1' when "011010101",
            '1' when "011010011",
            '1' when "011010100",
            '1' when "011010010",
            '0' when "011010000",
            '0' when "011001111",
            '1' when "011001110",
            '0' when "011001010",
            '1' when "011110000",
            '1' when "011110001",
            '1' when "011001100",
            '1' when "011001101",
            '0' when "011001001",
            '1' when "011001011",
            '0' when "011000011",
            '0' when "011001000",
            '1' when "011000111",
            '1' when "011000101",
            '1' when "011000110",
            '0' when "011000001",
            '0' when "011000100",
            '0' when "011000010",
            '0' when "011000000",
            '0' when "010111110",
            '0' when "010111101",
            '0' when "010111111",
            '1' when "011101111",
            '1' when "010111000",
            '1' when "010110111",
            '1' when "010110110",
            '1' when "011011000",
            '0' when "011101110",
            '1' when "010110101",
            '0' when "011011010",
            '1' when "010110100",
            '1' when "010110011",
            '0' when "010110010",
            '1' when "011010111",
            '0' when "010110001",
            '1' when "010110000",
            '1' when "010101111",
            '1' when "010101101",
            '1' when "010101100",
            '0' when "010101110",
            '1' when "010101011",
            '0' when "011011011",
            '1' when "010101001",
            '1' when "010101010",
            '0' when "010100110",
            '1' when "010101000",
            '0' when "010100101",
            '0' when "010100100",
            '0' when "010100011",
            '0' when "010100111",
            '1' when "011101011",
            '1' when "010010010",
            '0' when "010100001",
            '1' when "011101101",
            '0' when "010010101",
            '0' when "010100010",
            '0' when "010100000",
            '1' when "010011000",
            '1' when "010010100",
            '1' when "010010111",
            '1' when "010010110",
            '0' when "011101100",
            '1' when "010010011",
            '0' when "011011110",
            '0' when "011011100",
            '0' when "011011101",
            '0' when "011100000",
            '0' when "011011111",
            '0' when "011100001",
            '0' when "011100010",
            '0' when "011100100",
            '0' when "011100011",
            '0' when "011100101",
            '0' when "011100110",
            '0' when "011101000",
            '0' when "011100111",
            '1' when "011101001",
            '0' when "011101010",
            '1' when "011110010",
            '1' when "010010001",
            '-' when others;

    p_0_out <= res_overflow_0_reg_0;
    u_fp_mul : fp_mul
        port map (
            aclk => clk,
            s_axis_a_tdata => op_1,
            s_axis_a_tvalid => en,
            s_axis_b_tdata => op_2,
            s_axis_b_tvalid => en,
            m_axis_result_tdata => mul_result,
            m_axis_result_tvalid => mul_result_tvalid_unused
        );
    addsub_a <= (others => '0') when do_addsub = '0' else op_0;
    addsub_op <= "0000000" & (not is_add and do_addsub);
    process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                mul_result_reg <= mul_result;
            end if;
        end if;
    end process;
    mul_result_in <= mul_result_reg;
    u_fp_addsub : fp_addsub
        port map (
            aclk => clk,
            s_axis_a_tdata => addsub_a,
            s_axis_a_tvalid => en,
            s_axis_b_tdata => mul_result_in,
            s_axis_b_tvalid => en,
            s_axis_operation_tdata => addsub_op,
            s_axis_operation_tvalid => en,
            m_axis_result_tdata => res_arith_0,
            m_axis_result_tvalid => fp_result_tvalid
        );
    res_quant_0 <= res_arith_0(31 downto 0);
    res_overflow_0 <= res_quant_0(31 downto 0);

end architecture rtl;

