--
-- This code was automatically generated by the B-ASIC toolbox.
-- Code generation timestamp: (2026-06-07 23:44:49.151476)
-- B-ASIC version: 0.1.0.dev970+unknown.g621314118
-- URL: https://github.com/b-asic-eda/b-asic
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity rec0 is
    port (
        clk : in std_logic;
        en : in std_logic;
        schedule_cnt : in unsigned(10 downto 0);
        p_0_in : in std_logic_vector(31 downto 0);
        p_0_out : out std_logic_vector(31 downto 0)
    );
end entity rec0;

architecture rtl of rec0 is
    signal res_overflow_0_reg_0 : std_logic_vector(31 downto 0) := (others => '0');
    signal p_0_in_reg_0 : std_logic_vector(31 downto 0) := (others => '0');
    signal op_0 : std_logic_vector(31 downto 0);
    component fp_rec
        port (
            aclk : in std_logic;
            s_axis_a_tdata : in std_logic_vector(31 downto 0);
            s_axis_a_tvalid : in std_logic;
            m_axis_result_tdata : out std_logic_vector(31 downto 0);
            m_axis_result_tvalid : out std_logic
        );
    end component fp_rec;
    signal res_arith_0 : std_logic_vector(31 downto 0);
    signal fp_result_tvalid : std_logic;
    signal res_quant_0 : std_logic_vector(31 downto 0);
    signal res_overflow_0 : std_logic_vector(31 downto 0);

begin
    process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                res_overflow_0_reg_0 <= res_overflow_0;
                p_0_in_reg_0 <= p_0_in;
            end if;
        end if;
    end process;
    op_0 <= p_0_in_reg_0;
    p_0_out <= res_overflow_0_reg_0;
    u_fp_rec : fp_rec
        port map (
            aclk => clk,
            s_axis_a_tdata => op_0,
            s_axis_a_tvalid => en,
            m_axis_result_tdata => res_arith_0,
            m_axis_result_tvalid => fp_result_tvalid
        );
    res_quant_0 <= res_arith_0(31 downto 0);
    res_overflow_0 <= res_quant_0(31 downto 0);

end architecture rtl;

